### ISSUE TITLE
Fix Spelling in main UX

### ISSUE THREAD

**Issue by Boymeetsmill** [FormerLurker/Octolapse#101]
There is a spelling error in the UX. At the bottom I believe is supposed to be "Extruder" but is labeled as "Extrider"

Great plugin-overall! Thank you.

<img width="320" alt="octolapse_ss_03 25 2018" src="https://user-images.githubusercontent.com/37817669/37936763-84631c8a-310b-11e8-8df4-61fd626d034f.png">

**Comment by FormerLurker** [comment]
Umm it was a lord of the rings reference??  LOL, thanks for the catch, updating now!

**Comment by FormerLurker** [comment]
Fixed, Closed, Thanks!
