### ISSUE TITLE
Support non-cartesian printers

### ISSUE THREAD

**Issue by FormerLurker** [FormerLurker/Octolapse#13]
These are not currently supported.  I hope to include support for these at some point, but I don't own one to test on currently.

**Comment by FormerLurker** [comment]
At least one user has actually gotten one of these to work!  I added the beta profile to v0.2.4

**Comment by FormerLurker** [comment]
Note:  Octolapse cannot yet determine in or out-of-bounds positions when using a circular bed.  I understand lots of deltas have these.  For now you will need to use your bed diameter and define a rectangle of this size within your printer volume settings (either in the Octolapse Printer Profiles or within the OctoPrint printer profile, depending on your Octolapse Printer Profile settings).

**Comment by etrigan63** [comment]
> Note: Octolapse cannot yet determine in or out-of-bounds positions when using a circular bed. I understand lots of deltas have these. For now you will need to use your bed diameter and define a rectangle of this size within your printer volume settings (either in the Octolapse Printer Profiles or within the OctoPrint printer profile, depending on your Octolapse Printer Profile settings).

By this do you mean a rectangle that is circumscribed by the bed diameter (ie, fits inside of the circle) or a rectangle that contains the bed diameter (in essence a square that is as big as the circle)?

**Comment by FormerLurker** [comment]
You'll need to use a square that completely encloses the circle.  However, I strongly recommend that you use the 'center' stabilization since some of the other stabilizations (back left, back right, front left, front right) would attempt to put your extruder outside of your bed which could be bad depending on your firmware (note that some firmware will not allow the nozzle to go out of bounds, which would lessen the severity of the issue).

I can't believe I haven't fixed this yet.  Soon I'll add a drop down box for 'bed shape' that should take care of this once and for all.

Thanks for your post!

**Comment by FormerLurker** [comment]
This has been solved and will be included starting with V0.4!!!
