### ISSUE TITLE
Print is not starting with octolapse on

### ISSUE THREAD

**Issue by Railgunner13F** [FormerLurker/Octolapse#132]
#### If this is a feature request describe it here

FEATURE_REQUEST_DESCRIPTION_GOES_HERE

#### Version of Octolapse
 
Octolapse Version: Octolapse Vv0.3.0rc1

#### Version of OctoPrint

OctoPrint Version: OctoPrint 1.3.7rc4 running on OctoPi 0.14.0

#### When you ran into the problem, did you have diagnostic logging enabled?

Diagnostic Logging was Enabled: YES

#### What were you doing when the problem occurred

1. Start print from octoprint with octolapse enabled
2. Printer heats up to setpoint
3. printer moves to priming position and primes
4. before test line is extruded onto the bed the printer moves to center of bed and waits.
5. printer is unresponsive until I reset the firmware.

#### What should have happened?
Printer should have began printing and taking snapshots.

#### What happened instead?
 printer is unresponsive until I reset the firmware.

#### Operating System running OctoPrint and Octolapse

OS Name: OctoPi 
Os Version: 0.14.0

#### Printer model & used firmware incl. version

Printer Model: Duet Wifi powered custom CoreXY Voron
Printer Firmware Version: RepRapFirmware for Duet WiFi version 1.19

#### Browser and version of browser, operating system running browser

Browser: Chrome 65.0.3325.181 (Official Build) (64-bit)
Browser OS: Win7

#### Link to the gcode file you were printing when the problem occurred

Link to Gcode File: https://pastebin.com/GHPzYvN7

#### Link to settings.json

Link to settings.json with all passwords removed: SETTINGS_JSON_LINK_GOES_HERE

#### Link to plugin_octolapse.log

Link to plugin_octolapse.log:  https://pastebin.com/qQJs23Vp

#### Link to octoprint.log

Link to octoprint.log:  https://pastebin.com/nBQQmNJv

#### Link to contents of Javascript console in the browser

Link to javascript console output: https://pastebin.com/bAaBmwb5

#### Screenshots and/or videos of the problem:

Screenshot/Video Links: LINKs_GO_HERE

**Comment by FormerLurker** [comment]
Thanks for creating the issue!  It looks like there is a lot of data missing from plugin_octolapse.log.  Can you double check the debug profile settings and make sure all of the check boxes after 'Log Additional Information' are checked and try another print?  If they are all ticked, maybe run another print and just re-upload plugin_octolapse.log?  Very sorry to make you repost this, I know it is a pain :(

Also, the serial.log file (if enabled within Octoprint) will contain everything from the terminal window PLUS timestamps, which are very helpful.  If you can get me that file as well I would be grateful!

The only thing I noticed so far is that your printer did return a location when Octolapse asked for one (m114), but it looks like the serial communication stopped working.  Now to determine exactly when and why.

**Comment by Railgunner13F** [comment]
redid the print with he same effect. full Octolapse debug file here https://pastebin.com/TW3zmQsr

**Comment by FormerLurker** [comment]
This log contains better data, thanks! I will review asap.

**Comment by FormerLurker** [comment]
Hey, when you have some time would you reinstall octolapse from the plugin manager with the following URL:  https://github.com/FormerLurker/Octolapse/archive/devel.zip

You should NOT have to uninstall octolapse first if you don't want to.

Let me know if it accepts the G92 for homing the X, Y and Z axis now.  Please watch your printer like a hawk during and after the G92 is sent, I haven't tested this with my machine yet (I'm working on a G92 test gcode file, but it will take me a while).

**Comment by FormerLurker** [comment]
Holy cow I responded to the wrong issue!  Please IGNORE MY ADVICE, sorry :(

**Comment by Railgunner13F** [comment]
your responses seem to be accurate for my issue. Which advice was wrong?

**Comment by FormerLurker** [comment]
I've been looking hard at this issue, and I think I finally understand.  I need to think about how to solve this problem in a more general case, and I'm going to try to have it figured out this weekend.  I'll send you instructions on how to install the fix as soon as it's ready.  Thanks again for pointing out this issue!

**Comment by curtu** [comment]
try it on the next version of chrome. i have problem with another printing plugin on actual chrome 65. test the canary build 67

**Comment by FormerLurker** [comment]
@Railgunner13F,  I'm still looking into this, but it's more complicated than I thought.  I'm still not sure if this is an Octolapse or an Octoprint problem.  Anyway, I have NOT forgotten about your issue!

@curtu, i'll check out canary build 67 this weekend.  Fingers crossed.  I've had to do a lot of redevelopment in the last year because of major changes to chrome and FF.  I like progress but it sure is a lot of work!

**Comment by FormerLurker** [comment]
Hey @Railgunner13F  and @curtu, I think these problems have long been worked out and are now on the devel branch.  So much has changed I don't know where to start!  If you want to alpha test the latest code let me know.  I'm working hard on a new release and could always use testers.

Going to close this issue since it's stale, but feel free to open an new issue, or message me if you want more info.

Thanks!
