### ISSUE TITLE
Octolapse is creating funny errors

### ISSUE THREAD

**Issue by Blacksheep70** [FormerLurker/Octolapse#143]
#### Version of Octolapse
 
Octolapse Version: v0.3.1

#### Version of OctoPrint

OctoPrint Version: OctoPrint 1.3.7rc3 running on OctoPi 0.14.0

#### When you ran into the problem, did you have diagnostic logging enabled?

Diagnostic Logging was Enabled: YES

#### What were you doing when the problem occurred

1.) Load gcode
2.) Start printing

#### What should have happened?
Octolapse should have to record snapshots

#### What happened instead?
Octolapse started but created funny blinking pink error boxes (Position error)

```
Octolapse - Position Error
Position - Coordinates (X:None,Y:None,Z:None,E:40.94634) are out of the printer area! Cannot resume position tracking until the axis is homed, or until absolute coordinates are received.
```

#### Operating System running OctoPrint and Octolapse

OS Name: OctoPi
Os Version: 0.14

#### Printer model & used firmware incl. version

Printer Model: Creatlity 3D 10
Printer Firmware Version: Lates Marlin

#### Browser and version of browser, operating system running browser

Browser: Firefox
Browser OS: Win 10

#### Link to the gcode file you were printing when the problem occurred

https://blacksheeps.my-wan.de/nextcloud/index.php/s/4Mmw4gxJqeGKKqD

#### Link to settings.json

Link to settings.json with all passwords removed: 
https://blacksheeps.my-wan.de/nextcloud/index.php/s/4Mmw4gxJqeGKKqD

#### Link to plugin_octolapse.log

Link to plugin_octolapse.log:  https://blacksheeps.my-wan.de/nextcloud/index.php/s/4Mmw4gxJqeGKKqD

#### Link to octoprint.log

Link to octoprint.log:  https://blacksheeps.my-wan.de/nextcloud/index.php/s/4Mmw4gxJqeGKKqD

**Comment by FormerLurker** [comment]
Yes, this should work, but it doesn't.  See Issue #144, which I JUST created.  Two other users have reported this within the last 24 hours, but this bug has been around forever.  Thanks for reporting it.  I'm JUST now finishing my initial stab at fixing this, and will send you a link to upgrade to the newest version as soon as it's pushed.

Thanks for reporting!!!!

**Comment by FormerLurker** [comment]
Are you using one of the 'test mode' debug profiles?  These strip all extrusions, fan, temp control codes and maybe some others from the print.  It's meant as a way to test Ocotlapse settings and debug without actually printing or waiting for temps.

**Comment by Blacksheep70** [comment]
Full debug was enabled:

Full Diagnostic - Test Mode | Logs all optional information during a test print.

**Comment by FormerLurker** [comment]
Ah yes, that is why it was not extruding.  If you want a full log while printing do the Full Diagnostic - Live Print.

Also, unfortunately I can't fix this start gcode issue at the moment :(  Octoprint won't let me stop gcode processing while sending its own start gcode yet.  This causes race conditions that are pretty much impossible to solve.  I just sent a feature request that will hopefully take care of this, so fingers crossed!

I'll keep you in the loop, but am going to close this and will continue reporting in #144
