### ISSUE TITLE
feature request : embed mp3 to new created video ?

### ISSUE THREAD

**Issue by fred2088** [FormerLurker/Octolapse#145]
is it possible to include mp3 into newly created video ?

**Comment by FormerLurker** [comment]
It isn't right now.  So are you wanting a soundtrack or something similar to what youtube does regarding adding background music?

**Comment by fred2088** [comment]
yes, thanks

**Comment by Shadowen** [comment]
It's very easy to do this with an external program [Windows](https://support.microsoft.com/en-ca/help/4054502/windows-10-movie-maker-is-no-longer-available-for-download), [Mac](https://www.apple.com/ca/imovie/).

**Comment by Shadowen** [comment]
@fred2088 please confirm if the above solution helps you. I don't see a major need for this feature to be added. Let me know if you disagree.
