### ISSUE TITLE
Cr-10S 400 not triggering

### ISSUE THREAD

**Issue by djunisol** [FormerLurker/Octolapse#147]
#### If this is a feature request describe it here

FEATURE_REQUEST_DESCRIPTION_GOES_HERE

#### Version of Octolapse
 
Octolapse Version: 0.3.1

#### Version of OctoPrint

OctoPrint Version: 1.3.7

#### When you ran into the problem, did you have diagnostic logging enabled?

Diagnostic Logging was Enabled: NO

#### What were you doing when the problem occurred

turned on octolapse and then turned on a print

#### What should have happened?
it should start the octolapse

#### What happened instead?
the timer says waiting on home all axis

#### Operating System running OctoPrint and Octolapse

OS Name: Octopi
Os Version: 1.3.7

#### Printer model & used firmware incl. version

Printer Model: Creality CR10-S400
Printer Firmware Version: Th3d Unified Firmware

#### Browser and version of browser, operating system running browser

Browser: BROWSER_VERSION_GOES_HERE
Browser OS: BROWSER_OS_GOES_HERE

#### Link to the gcode file you were printing when the problem occurred

Link to Gcode File: GCODE_FILE_LINK_GOES_HERE

#### Link to settings.json

Link to settings.json with all passwords removed: SETTINGS_JSON_LINK_GOES_HERE

#### Link to plugin_octolapse.log

Link to plugin_octolapse.log:  LINK_GOES_HERE

#### Link to octoprint.log

Link to octoprint.log:  LINK_GOES_HERE

#### Link to contents of Javascript console in the browser

Link to javascript console output: LINK_GOES_HERE

#### Screenshots and/or videos of the problem:

Screenshot/Video Links: https://imageshack.com/a/img923/5347/NfMpwh.png
https://imageshack.com/a/img923/7774/0AA7NG.png

## Please consider becoming a patron
If you like this project, [please support my work by becoming a patron,](https://www.patreon.com/bePatron?u=9588101) and consider adding a 'star' to the repository.  It takes a lot of time and effort to maintain the project and respond to issues.  The cost of test prints, software, cameras, printer parts, etc. can quickly add up, so every bit helps.  I'm currently saving for some additional test cameras in preparation for develiping multi-camera support.

**Comment by FormerLurker** [comment]
Are you using start/end gcode scripts in OctoPrint?  If so, there are known issues that I'm working on right now.  The workaround is to move any start/end gcode into your slicer temporarily until the fix is ready.  Unfortunately I believe it will require and update within OcotPrint itself, so I'm not sure when that will happen.

If this is not the case can you post your gcode file please?  Also, if you want to try another print, send me a snapshot of the 'Position State' info panel, it contains more detailed information about homing/axis modes, etc...

Thanks for creating an issue!  We'll get it working!

**Comment by djunisol** [comment]
the start and end code's are already in cura (windows version)  i will get the gcode

**Comment by FormerLurker** [comment]
Great!  I'll wait for it and test right after work.

**Comment by djunisol** [comment]
changed the extension to txt to get it attached
[CCR10S4_PLActron_vase_delta_500seg.txt](https://github.com/FormerLurker/Octolapse/files/1929095/CCR10S4_PLActron_vase_delta_500seg.txt)

**Comment by djunisol** [comment]
well i'm doing this for a friend who is not good @ english
my cr10s runs fine and realy like this plugin
so he will try it and come back to you on that

**Comment by djunisol** [comment]
oh and if you need testers i'm game for that 😄

**Comment by FormerLurker** [comment]
What language does your friend speak?  I'm pretty good with german, but my
spanish is terrible :)

Regarding testers, you should follow Octolapse on Github and you'll see
when I push new commits.  There are instructions on the Installation page
of the github wiki that explain how to install the latest builds.  I would
be MOST appreciative if you are willing to test new features when they
appear.  I try to tie the commits to issues when possible, so it will be
obvious what has changed.

Thanks for helping your friend out!  That was very nice of you!

**Comment by djunisol** [comment]
He speaks Dutch (Netherlands)

**Comment by FormerLurker** [comment]
Have visited and loved every minute, but I'm glad your friend has a good translator!

**Comment by djunisol** [comment]
Can you make the changes in the gcode I attached and send it back cuz we are a bit lost haha
Best support ever man

**Comment by djunisol** [comment]
And then the code edits are not needed?

**Comment by FormerLurker** [comment]
No edits needed.  

However, this is safer if you want to change your gcode:

;FLAVOR:Marlin
;TIME:8190
;Filament used: 9.98936m
;Layer height: 0.3
;Generated with Cura_SteamEngine 3.2.1
M104 S205
M109 S205
M82 ;absolute extrusion mode
G90 ;absolute xyz axis mode
G28 ; home all axes
M501 ; Loads eeprom
M420 V ; Verify mesh
M420 S1 ; Activate Mesh
M205 X7 Y7 ; Lower Jerk to 7
M204 P500 T1000 ; Lower Acceleration
M117 Premature ejaculation...
G1 Z1.0 F3000 ; lift Z
G1 X0.2 Y25 Z0.2 F3000.0 ; move to start-line position
G92 E0 ; reset extruder
G1 X0.2 Y150.0 F1000.0 E15 ; draw 1st line
G1 X0.7 Y150.0 F3000.0 ; move to side 0.5mm
G1 X0.7 Y50 F1000.0 E30 ; draw 2nd line
G1 X0.7 Y25 F5000.0 ; quick wipe
G92 E0
M117 Ejaculating plastic...

**Comment by FormerLurker** [comment]
BTW, I like your LCD display text.  funny

**Comment by djunisol** [comment]
He will try now and I report back to you as soon as possible
And thanks for the compliment

**Comment by djunisol** [comment]
You sir are a genius
My hat of to you
It works with your tips :)

**Comment by FormerLurker** [comment]
Well it helps that I have seen this issue a few times already :)  I'm surprised that the G90's not in the default cura start gcode, and have been debating changing the default profile XYZ axis mode as I outlined above.  It leaves a bad taste in my mouth, but it's not a problem non-experts are likely to come across.

Be sure to post some timelapses to youtube so I can watch!  And let me know if you have any more trouble.

Also, tell your friend he is welcome to email me in Dutch (formerlurker@pm.me).  I can use google translate and have a few Dutch friends if things get out of hand.

Thanks for installing the plugin.  CLOSED!
