### ISSUE TITLE
Octolapse seems to be interfering with temperature commands and print initiation in general

### ISSUE THREAD

**Issue by thehammer2** [FormerLurker/Octolapse#152]
#### If this is a feature request describe it here

Not a Feature Request

#### Version of Octolapse
 
Octolapse Version: v0.3.1

#### Version of OctoPrint

OctoPrint Version: v1.3.8

#### When you ran into the problem, did you have diagnostic logging enabled?

Diagnostic Logging was Enabled: No logging was enabled

#### What were you doing when the problem occurred

1. I had successfully completed a print
2. Octolapse threw an error. I cannot be sure, but it may have been failure to synchronize. I wish I'd known the complete breakdown that was about to occur and I'd have paid more attention.
3. No rendered video was in the timelapse
4. I was also running autodelete on complete, so at some point, the gcode for the file I just printed was deleted
5. I loaded up another gcode and hit print.

#### What should have happened?
Beautiful, glorious printing.

#### What happened instead?
When starting printing after the moment described above, the print initiation is completely fragged when Octolapse is installed. Sometimes, NOTHING happens. It just sits there. Sometimes, no temperature commands are sent to the printer. The rest of the startup gcode goes off and the print gcode is sent. The print head starts moving, and extrusion codes are sent to the printer (I know it's getting those because it echos back that it is preventing undertemp extrusion), but at no point is the printer commanded to heat the bed or the hot end. I uninstalled Octolapse and everything works fine. Several restarts of OctoPrint/printer, uninstalls of Octolapse, reinstalls, etc., later and nothing helps. 

If Octolapse is installed, the print fails to start properly. If not, prints run.

#### Operating System running OctoPrint and Octolapse

OS Name: OctoPi
Os Version: 0.14.0

#### Printer model & used firmware incl. version

Printer Model: Monoprice Maker Ultimate
Printer Firmware Version: Marlin Ultimaker2; Sprinter/grbl mashup for gen6 FIRMWARE_URL:http://github.com/Ultimaker PROTOCOL_VERSION:1.0

#### Browser and version of browser, operating system running browser

Browser: Chrome Version 66.0.3359.139 (Official Build) (64-bit)
Browser OS: Windows 10 Home, v1709, build 16299.371

#### Link to the gcode file you were printing when the problem occurred

Link to Gcode File: https://gist.github.com/thehammer2/552b1ad80a07bf35e649a696af199f62

#### Link to settings.json

Link to settings.json with all passwords removed: Nah. I'll pass.

#### Link to plugin_octolapse.log

Link to plugin_octolapse.log:  No logs available from when the problem occurred

#### Link to octoprint.log

Link to octoprint.log:  No logs available from when the problem occurred

#### Link to contents of Javascript console in the browser

Link to javascript console output: Not a UI problem

#### Screenshots and/or videos of the problem:

Screenshot/Video Links: Nothing available. 

## Please consider becoming a patron
If you like this project, [please support my work by becoming a patron,](https://www.patreon.com/bePatron?u=9588101) and consider adding a 'star' to the repository.  It takes a lot of time and effort to maintain the project and respond to issues.  The cost of test prints, software, cameras, printer parts, etc. can quickly add up, so every bit helps.  I'm currently saving for some additional test cameras in preparation for develiping multi-camera support.

**Comment by FormerLurker** [comment]
I think this is a known issue, but need to see your start gcode.  There is
both a workaround and a devel branch fix (not ready for public
consumption).   Soon you will have your glorious prints AND a smooth
timelapse...

**Comment by thehammer2** [comment]
Start gcode...

;Sliced at: {day} {date} {time}
G21 ;metric values
G90 ;absolute positioning
M82 ;set extruder to absolute mode
M107 ;start with the fan off
G28 X0 Y0 ;move X/Y to min endstops
G28 Z0 ;move Z to min endstops
G1 Z15.0 F{travel_speed} ;move the platform down 15mm
G92 E0 ;zero the extruded length
G1 F{travel_speed}
M117 Printing...

**Comment by FormerLurker** [comment]
Hmmm, I don't see any code there for setting the temp.  Maybe you could copy from the gcode file instead of from your slicer?

**Comment by thehammer2** [comment]
Yep. That's the start code from the slicer. Here's the code as it comes out of the slicer.

;FLAVOR:Marlin
;TIME:2583
;Filament used: 1.31038m
;Layer height: 0.1
;Generated with Cura_SteamEngine 3.3.1
M190 S60
M104 S205
M109 S205
M82 ;absolute extrusion mode
;Sliced at: Sat 28-04-2018 13:07:46
G21 ;metric values
G90 ;absolute positioning
M82 ;set extruder to absolute mode
M107 ;start with the fan off
G28 X0 Y0 ;move X/Y to min endstops
G28 Z0 ;move Z to min endstops
G1 Z15.0 F{travel_speed} ;move the platform down 15mm
G92 E0 ;zero the extruded length
G1 F{travel_speed}
M117 Printing...

**Comment by mplewis** [comment]
> Sometimes, no temperature commands are sent to the printer. The rest of the startup gcode goes off and the print gcode is sent.

I have this same issue with my prints. When I hit Print, the printer goes through homing, clearing the extruder, and starting the print. I expect it to wait for the bed to heat, then wait for the extruder to heat, then home and continue.

Printer: CR-10
Profile: CR-10 (Beta)

Example start Gcode, pulled from a file that failed when Octoprint was installed, but worked when Octoprint was removed:

```
; generated by Slic3r Prusa Edition 1.39.2+linux64 on 2018-05-18 at 18:32:52

; 

; external perimeters extrusion width = 0.45mm
; perimeters extrusion width = 0.45mm
; infill extrusion width = 0.45mm
; solid infill extrusion width = 0.45mm
; top infill extrusion width = 0.40mm

M107
M190 S60 ; set bed temperature and wait for it to be reached
; XYZE steps
M92 X79.87 Y81.40 Z404.34 E95.40
; XY jerk
M205 X30.00
; PID tune
M301 H1 P35.11 I3.27 D94.33 ; 200 C, volcano block, fan off

M117 Heating extruder.
M109 S210

M117 Homing axes.
G28

M117 Purging extruder.
G1 Z1.0 F3000 ; lift Z
G1 X2.0 Y25 Z0.2 F3000.0 ; move to start-line position
G92 E0 ; reset extruder
G1 X2.0 Y150.0 F1000.0 E15 ; draw 1st line
G1 X2.5 Y150.0 F3000.0 ; move to side 0.5mm
G1 X2.5 Y50 F1000.0 E30 ; draw 2nd line
G1 X2.5 Y25 F5000.0 ; quick wipe

M117 Printing!
; Filament gcode
G21 ; set units to millimeters
G90 ; use absolute coordinates
M82 ; use absolute distances for extrusion
G92 E0
```

**Comment by FormerLurker** [comment]
Just to clarify, neither of you are using test mode, right?  In other words, debug mode = live print?

**Comment by mplewis** [comment]
I am not using test mode, as far as I know. I can try again tonight, with a screenshot of my Octolapse panel, and make sure.

**Comment by FormerLurker** [comment]
Thanks, that will help.  Maybe post your settings.json file too?  It can be exported from the Octolapse settings page (not the tab).

**Comment by bluemeane** [comment]
I have this same issue with my Prusa MK3. Was driving my crazy until I realized it was this plugin I just installed lol

**Comment by bluemeane** [comment]
I noticed that the problem came after I installed, and turned on Octlapse. I had the plugin installed for a while, but I never used it, or configured it. I then did so, but hadn't started a print for a couple of days, and once I did I was racking my brain trying to figure out what was wrong. Then I remembered I had turned on this plugin, so I turned it off, and tried a print again, and BAM! I was up and running again.

Same exact issue as everyone in this thread, with it on, whatever it injects into the gcode is making it so that the initial temp codes are not sent to the printer.

**Comment by mplewis** [comment]
@FormerLurker Sorry for taking so long; here are [my settings](https://gist.github.com/mplewis/7651cf5006e61c10fe4944a1190d8af3) and a screenshot.
![2018-05-31-003745_630x748_scrot](https://user-images.githubusercontent.com/1829094/40765878-1ed752d0-646b-11e8-85b4-5019e2a9e700.png)

**Comment by FormerLurker** [comment]
So very sorry for the long delay between updates here, but I think this issue has been addressed in the latest development build.  You can install the development version 0.3.2 by using the plugin manager within Octoprint with the following install URL:  https://github.com/FormerLurker/Octolapse/archive/devel.zip

Please let me know if this solves your problem.  When you try it out please make sure to use the following debug profile:  Full Diagnostic - Live Print

If there are any problems, please post your logs.  Thanks!

**Comment by FormerLurker** [comment]
This has been fixed in the latest release candidate for sure (https://github.com/FormerLurker/Octolapse/archive/v0.3.3rc2.zip).  Please comment in this issue regarding the release candidate if you run into issues:  https://github.com/FormerLurker/Octolapse/issues/198

I'll re-open this issue if there are further problems, but for now I'm going to assume this is closed.
