### ISSUE TITLE
Please add a option to prevent octolapse from caseling the print when printing from sd card

### ISSUE THREAD

**Issue by CamoJackson** [FormerLurker/Octolapse#153]
It just gets annoying that i have to disable it in plugin manager when im printing from sd

**Comment by FormerLurker** [comment]
Someone else just asked me to do this.  I think i will.  I will hopefully
have time after next weekend (out of town).

Thanks for your request!

**Comment by FormerLurker** [comment]
This took a bit longer than I'd hoped, but it has been added and is on the devel branch.  Let me know if you want to try it out!  

I'm going to close this issue since we have two going now.  I'll reopen if you want to discuss more.  Let me know!
