### ISSUE TITLE
Themeify compatibility

### ISSUE THREAD

**Issue by foodbandlt** [FormerLurker/Octolapse#154]
#### If this is a feature request describe it here

Just thought this would be a cool touch.  Right now a lot of background colors and text colors are explicitly defined.  Was wondering if you'd be willing to define them as "inherit" to play nice with themes that define text and background colors at the top level.  Not sure how this plays with the regular Octoprint theme so it would require testing, but if you have time this would be great!

https://i.imgur.com/z5XZqTy.png

#### Version of Octolapse
 
Octolapse Version: 0.3.1

#### Version of OctoPrint

OctoPrint Version: 1.3.8

**Comment by FormerLurker** [comment]
I've seen some screen caps with that plugin enabled and have noticed that
it doesn't play nicely.  As soon as I have some time I'll install the
plugin and see if I can't find some simple changes to at least improve
things.  I'll let you know how that goes.

Thanks for the suggestion!

**Comment by FormerLurker** [comment]
@foodbandlt, I just pushed an initial commit that should fix things somewhat for Octolapse and themeify, though there is definitely more work to be done.  It looks pretty good with the default theme :)

The code is in the devel branch.  If you want to try it out feel free.  Lots has changed, and there is some new (less tested) functionality in there.

**Comment by FormerLurker** [comment]
This is working now in v0.3.4!  Closed.
