### ISSUE TITLE
Synchronisation failed No frames captured 

### ISSUE THREAD

**Issue by oliclarke** [FormerLurker/Octolapse#155]
Octolapse Version: 0.3.1
OctoPrint Version: 1.3.8

Trying to make an orbiting lapse on a custom AM8 style printing, using the anet A8 profile, snapshot at layer change, fixed length mp4 00:30.  No frames are captured during the print. Once finished or cancelled i get an error ''synchronisation failed, no frames captured. 
I have had multiple different errors, but this is the one i am seeing now.

OS Name: octopi 
Os Version: 1.3.8
Printer Model: custom AM8 style
Printer Firmware Version: 1.9x bugfix marlin
Browser: chrome
Browser OS: windows 10
Link to Gcode File: https://pastebin.com/NdYM7gaY

**Comment by FormerLurker** [comment]
Whoops, didn't mean to close the issue!  Reopened.

**Comment by hk89** [comment]
I do have the same issue even with G90 and M82 commands inserted in gcode

OS Name: octopi
Os Version: 1.3.8
Printer Model: Generic Reprap
Printer Firmware Version: 1.1.8 marlin
Slicer: Simplify3D(R) Version 3.1.0
Browser: opera
Browser OS: windows 10
Link to Gcode File: https://pastebin.com/raw/cesNeity

**Comment by FormerLurker** [comment]
@hk89,  I believe your issue has been solved in the latest master branch, which you can install manually within the plugin manager by using the following URL:

https://github.com/FormerLurker/Octolapse.git

Warning:  There are a few known and undocumented bugs in the current version, but it should get you up and running.

@oliclarke, can you let me know if the changes I suggested have solved your issue?

Also, just so you both know, I'm in the process of fixing a major (and previously unfixable) issue with start gcode in Octoprint due to yet another awesome feature that Gina has added to Octoprint.  If you have any start/end GCode that is stored within Octoprint itself, consider moving it into your slicer for the time being.

**Comment by hk89** [comment]
`Installing plugin from https://github.com/FormerLurker/Octolapse.git...
/home/pi/oprint/bin/python2 -m pip install https://github.com/FormerLurker/Octolapse.git
Collecting https://github.com/FormerLurker/Octolapse.git
Downloading https://github.com/FormerLurker/Octolapse.git
Cannot unpack file /tmp/pip-aozXes-unpack/Octolapse.git (downloaded from /tmp/pip-MI4IoL-build, content-type: text/html; charset=utf-8); cannot detect archive format
Cannot determine archive format of /tmp/pip-MI4IoL-build
You are using pip version 9.0.3, however version 10.0.1 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
Error!
Could not parse output from pip, see plugin_pluginmanager_console.log for generated output`

@FormerLurker I'm getting this error

**Comment by FormerLurker** [comment]
Do you know how to upgrade pip?  That should fix this error.

**Comment by FormerLurker** [comment]
Sorry this took a while!  Just connect to the pi and run the following command:

pip install --upgrade pip

Let me know if that works and I'll close the issue!

**Comment by willjkeller** [comment]
I am running OctoPrint 1.3.8 running on OctoPi 0.14.0 .

I couldn't get the plugin to install from the plugin manager. I got pip errors and it some problems unpacking the repo. To upgrade over ssh:
> connect as `pi`
> source ~/oprint/bin/activate
> pip install git+https://github.com/FormerLurker/Octolapse.git

Works for me now! Thanks.

**Comment by hk89** [comment]
Sorry about the late reply but my Pi refuses my credentials for SSH (access denied).

I tried:
Username : pi
Password: raspberry

**Comment by FormerLurker** [comment]
I'm guessing you probably changed your password at some point.  If you didn't, I'd recommend you reflash and start over.  If you didn't change your password, maybe somebody else did?  Are you using port-forwarding to allow access to your OctoPrint instance by chance?  In any case I don't think this password is something you can recover, though I could be wrong.

**Comment by hk89** [comment]
I don't think I have changed my credentials to octopi. However I changed the access control credentials in octoprint on the first time run. Please help me.

**Comment by FormerLurker** [comment]
That shouldn't change your root user password.  Are you 100% sure you are entering it correctly (i have to ask)?  I'm assuming you have connected successfully in the past.

Why not reflash your instance with the latest OctoPi version?  You will have to re-configure, but it really doesn't take too long.  I know you will probably lose things you would rather keep.

There is another possibility, but it will require some waiting.  I hear that a new feature will be added to Octoprint soon (unknown exactly when) that will let you back up your settings.  Then you could re-flash your sd card and restore your backup settings.  That should allow you to connect via SSH again AND to keep your current settings/files.

**Comment by willjkeller** [comment]
@hk89 what client are you using? What happens when you ping the ip?

the python you get in the shell is a different python environment than the one octoprint uses, so you have to make sure you're upgrading the right one,

**Comment by FormerLurker** [comment]
@willjkeller, I think @hk89 is having trouble connecting to SSH due to a forgotten password.  However, your post is correct, and when @hk89 figures their password out, pip should be upgraded using the method you mentioned:
```
pi@octopi:~ $ source oprint/bin/activate
(oprint)pi@octopi:~ $ pip install --upgrade pip
```

**Comment by hk89** [comment]
@FormerLurker I am absolutely certain I did not change any password other than the access control credentials during the first setup of octoprint. I tried that password and it did not work either.

@willjkeller I am using PuTTY 0.7 and using the fixed assigned IP address of my Pi. I can then connect successfully. Regarding pinging the IP address, I did not do it but I will try. I guess I will get a reply because I can access octoprint.

**Comment by FormerLurker** [comment]
@hk89,

Are you copying and pasting your password into the terminal?  If so, keep in mind that a single right click will paste for you.  I'm guessing this isn't your issue, but it never hurts to check.

Maybe [this link](http://mapledyne.com/ideas/2015/8/4/reset-lost-admin-password-for-raspberry-pi) will help?  I have NOT tried this and the link is a few years old, but it might be worth a shot.  If you can, it wouldn't be a bad idea to create a backup of your SD card first, just in case.

**Comment by hk89** [comment]
@FormerLurker that's a pretty useful page you gave me. I'll try it and report back.

**Comment by hk89** [comment]
@FormerLurker  It worked!! Thanks a lot. Now having an upgraded pip I can install the plugin.

**Comment by FormerLurker** [comment]
@hk89, Woot!  I'm very glad.  I'll keep that link in my tool belt for future use :)

**Comment by FormerLurker** [comment]
So, this is a very old issue that I've neglected to close.  Thanks for all of your posts/contributions!
