### ISSUE TITLE
Octolapse with DisplayZ overwrites actual height

### ISSUE THREAD

**Issue by Phil1988** [FormerLurker/Octolapse#166]
#### Version of Octolapse
Octolapse Version: Octolapse v0.3.1

#### Version of OctoPrint
OctoPrint Version: OctoPrint 1.3.8 

#### When you ran into the problem, did you have diagnostic logging enabled?
Diagnostic Logging was Enabled: I dont know

#### What were you doing when the problem occurred
1. Installed the DisplayZ Plugin
2. Installed OctoLapse
3. Print something
4. After every snapshot the current Z height is somehow 'overwritten' after the image is captured
5. The print continues, the hotend goes a bit down for that reason and the current Z height is displayed as **-0.20mm**

#### What should have happened?
The height should be displayed as the correct value.

#### What happened instead?
The height is always -0.20mm (but the screen on the printer tells the correct height.. just not on octopi)

#### Operating System running OctoPrint and Octolapse
OS Name: OctoPi
Os Version: 0.14.0

#### Printer model & used firmware incl. version
Printer Model: Creality CR-10
Printer Firmware Version: Marlin (cant see the FW version right now, because I'm 9,5h in a 12h print :D )

#### Screenshots and/or videos of the problem:
Screenshot/Video Links: https://www2.pic-upload.de/img/35334153/Octolapse.png

**Comment by FormerLurker** [comment]
That's odd.  I'm not sure why Octolapse would interfere with the DisplayZ
Plugin.  Have you contacted the developer of that plugin?  I've never used
it myself.

FYI, Octolapse also can display the current Z height within the Position
info panel (octolapse tab).  Maybe you can enable that (can be done while
printing) and see what it says there.

If Octolapse knows what layer it is on, and is correct, then perhaps the
problem is with DisplayZ?  Let me know what you find out.

Thanks!

**Comment by FormerLurker** [comment]
While the print is running, click on 'Position State' and 'Position Changes' to see the info panel.  I can't remember which one has the z-height ATM, but it's definitely one of those two.  You should check out the info panels, they take some bandwidth, but are pretty neat IMO and give good information.

**Comment by FormerLurker** [comment]
OH, I didn't notice that Gina wrote that plugin!  I should have looked :)

**Comment by ukwebb** [comment]
Isee this same issue . The Octolapse Position State tabe doesnt help as i can see the zheight on my screen via the M117 command, thanks to the plugins.
The displays all seems to reflect the last change in height - Mine is always -0.10 which is the z-hop height.  
I think the original print job gcode may be setting the correct absolute height, then octolapse moves up relative by its zhop distance (ie +0.10) , then back down relative afterwards (ie -0.10)
this could probably be fixed if octolapse adds its zhop height to the current height, then sets it back but using absolute values all the way.

**Comment by FormerLurker** [comment]
So the display z plugin must not be taking the g90/g91 commands into consideration, or is not intercepting them.  I wonder if this could be recreated with only gcode, or if it is specific to plugins that inject gcode.

**Comment by ukwebb** [comment]
Maybe You guys could work together  to a fix ?

https://github.com/OllisGit/OctoPrint-DisplayLayerProgress/issues/48

**Comment by FormerLurker** [comment]
I think this issue has been more or less solved.  In any case the 'DisplayLayerProgress' plugin needs to be modified to get rid of the issue 100%.  If you want me to reopen, just reply and I will do so.

Thanks for posting!
