### ISSUE TITLE
Stalls Print - Hard Locks Octoprint 

### ISSUE THREAD

**Issue by RJ-Make** [FormerLurker/Octolapse#186]
#### If this is a feature request describe it here

FEATURE_REQUEST_DESCRIPTION_GOES_HERE

#### Version of Octolapse
 
Octolapse Version: v0.3.1

#### Version of OctoPrint

OctoPrint Version: 1.3.9rc2

#### When you ran into the problem, did you have diagnostic logging enabled?

Diagnostic Logging was Enabled: No

#### What were you doing when the problem occurred

1. Started print
2. Printed started, 
3. Print stalls, and hard locks OctoPrint

#### What should have happened?
Printed should have completed with out issue and does when I disable Octolapse

#### What happened instead?
Print stalls, and hard locks OctoPrint

#### Operating System running OctoPrint and Octolapse

OS Name: OctoPi
Os Version: 0.13.0

#### Printer model & used firmware incl. version

Printer Model: Monoprice Select Mini V1
Printer Firmware Version: 35.

#### Browser and version of browser, operating system running browser

Browser: BROWSER_VERSION_GOES_HERE
Browser OS: BROWSER_OS_GOES_HERE

#### Link to the gcode file you were printing when the problem occurred

Link to Gcode File: GCODE_FILE_LINK_GOES_HERE

#### Link to settings.json

Link to settings.json with all passwords removed: SETTINGS_JSON_LINK_GOES_HERE

#### Link to plugin_octolapse.log

Link to plugin_octolapse.log:  LINK_GOES_HERE

#### Link to octoprint.log

Link to octoprint.log:  LINK_GOES_HERE

#### Link to contents of Javascript console in the browser

Link to javascript console output: LINK_GOES_HERE

#### Screenshots and/or videos of the problem:

Screenshot/Video Links: LINKs_GO_HERE

## Please consider becoming a patron
If you like this project, [please support my work by becoming a patron,](https://www.patreon.com/bePatron?u=9588101) and consider adding a 'star' to the repository.  It takes a lot of time and effort to maintain the project and respond to issues.  The cost of test prints, software, cameras, printer parts, etc. can quickly add up, so every bit helps.  I'm currently saving for some additional test cameras in preparation for develiping multi-camera support.

**Comment by gege2b** [comment]
seems like we face [the same problem](https://github.com/foosel/OctoPrint/issues/2677) but with different versions

It would be great to have some logs

**Comment by lewnewby** [comment]
I put logs into Issue #183 as I can repeat this over and over with confidence.

**Comment by FormerLurker** [comment]
Thanks for all of your reports and especially your logs.  I just finished up (fingers crossed) another fix and am looking at this now.  I'll update ASAP with further developments.

**Comment by FormerLurker** [comment]
I'm moving this to issue #183 since this is the same prroblem.  Please comment there from now on, thanks!
