### ISSUE TITLE
Fix FFMPEG check

### ISSUE THREAD

**Issue by FormerLurker** [FormerLurker/Octolapse#210]
The FFMpeg check breaks silently if there is no path entered.  Need to check for an exception and send an appropriate message to the client.

**Comment by Shadowen** [comment]
On Octolapse v0.3.3rc2 (`rc/devel`?), when I try to start with no ffmpeg path set in OctoPrint, I get the following error on print start:

![screenshot from 2018-08-03 00-44-10](https://user-images.githubusercontent.com/8551479/43624597-6e205620-96b6-11e8-9f91-3400c7f3b80d.png)

I also tested at `devel` `HEAD`. Can you give some replication instructions?

**Comment by FormerLurker** [comment]
I think it is maybe a Windows only issue.

**Comment by FormerLurker** [comment]
Unless I fixed it and forgot.  Saw it in a user log while debugging another issue.

**Comment by FormerLurker** [comment]
I think this problem only exists when no value was ever entered in the OctoPrint ffmpeg location.  I was using the wrong version of get (should use global_get).  Closed.
