### ISSUE TITLE
Request - Disable stabilization movement when Z=0 + reduced speed

### ISSUE THREAD

**Issue by madmax2** [FormerLurker/Octolapse#259]
#### If this is a feature request describe it here

I have the setting stabilization setting
**Fixed Extruder at Center**

I notice that when octoprint starts it normally homes all
Then when you press print the nozzle would make a violent really fast movement towards the center (due to the above setting) before returning to home all position and then begin the Gcode startup script 
and then start the print.

The problem is this violent fast movement should not be done at all when nozzle is at home all position
since Z=0.
I hear bad sound when it does this initial movement.
Mostly likely the nozzle probably scraping the heat bed + my glass bed.
Also the movement is way too fast and should be slower since the nozzle is so close to the bed.

I suggest the stabilization movement should not be done at such an early stage when the nozzle is still at Z=0.
It should be omitted until at least layer 1 etc or when Z is more than 0 to avoid this problem
OR the nozzle should move up by e.g. 3mm before doing this initial movement.
.
The speed of this first movement should also be reduced to protect our nozzle from scratching the heat bed etc..

#### Version of Octolapse
 
Octolapse Version: 0.3.1

#### Version of OctoPrint

OctoPrint Version: 1.3.9

#### When you ran into the problem, did you have diagnostic logging enabled?

Diagnostic Logging was Enabled: YES_OR_NO

#### What were you doing when the problem occurred

1. STEP_ONE_GOES_HERE
2. STEP_TWO_GOES_HERE
3. STEP_...

#### What should have happened?
PUT_YOUR_DESCRIPTION_HERE

#### What happened instead?
PUT_YOUR_DESCRIPTION_HERE

#### Operating System running OctoPrint and Octolapse

OS Name: OS_NAME_GOES_HERE
Os Version: OS_VERSION_GOES_HERE

#### Printer model & used firmware incl. version

Printer Model: PRINTER_MODEL_GOES_HERE
Printer Firmware Version: PRINTER_FIRMWARE_VERSION_GOES_HERE

#### Browser and version of browser, operating system running browser

Browser: BROWSER_VERSION_GOES_HERE
Browser OS: BROWSER_OS_GOES_HERE

#### Link to the gcode file you were printing when the problem occurred

Link to Gcode File: GCODE_FILE_LINK_GOES_HERE

#### Link to settings.json

Link to settings.json with all passwords removed: SETTINGS_JSON_LINK_GOES_HERE

#### Link to plugin_octolapse.log

Link to plugin_octolapse.log:  LINK_GOES_HERE

#### Link to octoprint.log

Link to octoprint.log:  LINK_GOES_HERE

#### Link to contents of Javascript console in the browser

Link to javascript console output: LINK_GOES_HERE

#### Screenshots and/or videos of the problem:

Screenshot/Video Links: LINKs_GO_HERE

## Please consider becoming a patron
If you like this project, [please support my work by becoming a patron,](https://www.patreon.com/bePatron?u=9588101) and consider adding a 'star' to the repository.  It takes a lot of time and effort to maintain the project and respond to issues.  The cost of test prints, software, cameras, printer parts, etc. can quickly add up, so every bit helps.  I'm currently saving for some additional test cameras in preparation for develiping multi-camera support.

**Comment by FormerLurker** [comment]
I'm going to go ahead and close this duplicate issue (see #260).  Let me know if I should reopen it for any reason.
