### ISSUE TITLE
How to Import settings

### ISSUE THREAD

**Issue by phcoetzee** [FormerLurker/Octolapse#274]
Thanks for a great plugin FormerLurker. I want to know how can I import the settings that I backed up? I have two raspi 3b's running octopi and Octolapse with Logitech C270 cams. Octolapse is running smooth on pi1. If I download Settings.json from pi1 how can I import those same settings into pi2 so that the two pi's have exactly the same settings? I don't want to go through all the settings again on pi2. Thank you very much.

**Comment by FormerLurker** [comment]
Hi, thanks for posting the issue!  I plan to add an import option in the future, but for now you'll have to download the settings then manually place them in the new pi.  Here are the steps:

1.  Download the settings.json file from Octoprint Settings (wrench/spanner icon)->Octolapse.  There is a download button there (sounds like you are aware of that).

2.  Using SFTP navigate to home/pi/.octoprint/data/octolapse and overwrite the settings.json file there.

MAKE SURE you are using the same version of Octolapse on both PIs.  If not, upgrade both before you download.

Let me know if that helps!

**Comment by phcoetzee** [comment]
Thank you very much FormerLurker it worked! I just had to open settings.json with notepad++ and change the ip address to that of the new pi.

**Comment by FormerLurker** [comment]
Woot!  Glad to help!
