### ISSUE TITLE
Y-Shift while printing

### ISSUE THREAD

**Issue by jalanjarosz** [FormerLurker/Octolapse#277]
#### If this is a feature request describe it here

FEATURE_REQUEST_DESCRIPTION_GOES_HERE

#### Version of Octolapse

Octolapse Version: 0.3.4

#### Version of OctoPrint

OctoPrint Version: 1.3.9

#### When you ran into the problem, did you have diagnostic logging enabled?

Diagnostic Logging was Enabled: No

#### What were you doing when the problem occurred

1. Printing a large model, approx 195mm x 150mm
2. 
3. STEP_...

#### What should have happened?
Model should have maintained position across all axis'

#### What happened instead?
While printing, at random z-height, the model shifted, only in the Y-Direction, of various dimensions.

#### Operating System running OctoPrint and Octolapse
OS Name: Raspbian
Os Version: OctoPi version    : 0.15.1

#### Printer model & used firmware incl. version
Printer Model: Anet A8 with v1.5 controller
Printer Firmware Version: Marlin 1.1.9

#### Browser and version of browser, operating system running browser

Browser: n/a
Browser n/a

#### Link to the gcode file you were printing when the problem occurred

Link to Gcode File: http://myshare.nhtroop911.org/RLink/d/blnRrm7wJ

#### Link to settings.json

Link to settings.json with all passwords removed: http://myshare.nhtroop911.org/RLink/d/rXE7ld7jB

#### Link to plugin_octolapse.log

Link to octoprint.log:  Logging not active yet.

#### Link to contents of Javascript console in the browser

Link to javascript console output: LINK_GOES_HERE

#### Screenshots and/or videos of the problem:

Screenshot/Video Links: 
Photo of end result: http://myshare.nhtroop911.org/RLink/d/DNa5a0RGL
c920 video: http://myshare.nhtroop911.org/RLink/d/wVQ7NV7G9
HP video: http://myshare.nhtroop911.org/RLink/d/q9AvPjRQO

## Please consider becoming a patron
If you like this project, [please support my work by becoming a patron,](https://www.patreon.com/bePatron?u=9588101) and consider adding a 'star' to the repository.  It takes a lot of time and effort to maintain the project and respond to issues.  The cost of test prints, software, cameras, printer parts, etc. can quickly add up, so every bit helps.

You can find various [videos and tutorials](https://www.youtube.com/channel/UCnnTLQetNw7FqfQOLJCMqoQ) by subscribing to my Youtube channel.  You can also [follow me on Twitter](https://twitter.com/FormerLurker1).

**Comment by jalanjarosz** [comment]
Issue started happening after v0.3.4 was installed on 21nov.  I was using a RC build previous to that

**Comment by jalanjarosz** [comment]
Printing same large file with Octolapse turned off to see if I can get successful print.  Will advise hopefully later tonight.  

Happy Thanksgiving!

**Comment by FormerLurker** [comment]
Thanks you, and I hope you also have a happy holiday!

You might want to try turning your travel speed down a bit.  A while back I too had problems with shifting layers that I resolved by tightening my belt a bit.  If you continue to have issues, let me know.

**Comment by jalanjarosz** [comment]
Thanks for the response.   Before the last print, I changed the Y-Belt and made sure it was enough tension.  I don't "believe" it's a mechanical issue yet.    I'm 36% in the print and it's going well.

Being I'm printing at 80mm/s, do you think that Octolapse might not be able to keep up with this larger model?

**Comment by jalanjarosz** [comment]
I should ask.   If I run the "virtual" printer, do you think I could reproduce the issue?  I could turn on Octolapse logging.

**Comment by FormerLurker** [comment]
If there is a bug in the sent gcode, probably.  Turn off all logging except gcode sent and the snapshot gcode setting.  However, it will be a lot of data to review.

**Comment by FormerLurker** [comment]
Just curious, what is your travel speed setting in octolapse?

**Comment by jalanjarosz** [comment]
Travel speed is 160mm/s in Octolapse

**Comment by FormerLurker** [comment]
That is pretty high.  Are you running a Bowden setup or direct drive?

**Comment by FormerLurker** [comment]
Also, I'm not dismissing the possibility that octolapse is causing this.  I want to make that clear :)

**Comment by jalanjarosz** [comment]
Bowden and E3D.  I'm printing PETG right now.  The extra speed helps reduce blobs and strings.

**Comment by FormerLurker** [comment]
I'll look through the files you posted when I return from my Thanksgiving travels.  In the meantime please keep your log files, and maybe try dropping your travel speed by 50 mm/sec, then run some small test print to see if you still get layer shifts.  If it happens at really low speeds that will strengthen the likely hood that it is octolapse and not mechanical.

**Comment by jalanjarosz** [comment]
So you can gauge my setup:
Raspberry Pi 3B+, I have a good quality PSU with a good quality USB cable to power.
2 USB cam's  the c920 is HD in resolution, the HP is SD
Both cam's have been directly on the Pi, when it first happened, but I recently moved them to a powered USB 2.0 hub, just to reduce any chance the issue is Pi power related.

The SD Card is Samsung microSDXC UHS-1 card. Rated at 100mb/s read and 60mb/s write.

All my "small" prints come out 100% okay. So far, it's just this one BIG print.  Time estimated at 12-16hr to print.

**Comment by jalanjarosz** [comment]
Well, it appears to not be Octoprint related.
What I saw when it happened, is the nozzle dragged across the part and made it skip.   I'm adding in Z-Hop when retracted and Z-Hop over printed parts combined with slowing down travel speed.

Thanks for your willingness to check this out and providing some suggestions.

**Comment by jalanjarosz** [comment]
Issue is not Octolapse related.

**Comment by FormerLurker** [comment]
Of course, and thanks for posting!  I must admit I was a bit worried since I was also having layer shift issues, lol!  Fortunately it was just a coincidence.  Please let me know if you have any other issues or questions in the future.
