### ISSUE TITLE
Octolapse (0.3.4) Lost Printers list

### ISSUE THREAD

**Issue by infomagichand** [FormerLurker/Octolapse#280]
Octolapse Version: (0.3.4)

After i updated the Octolapte (0.3.4) plugin, i lose the list of the 3D printers, now i onlly have the one that was previous selected =(

i uninstalled the plugin and reinstalled without luck...it keeps only showing 1 printer in the list. =(
how can i fix this?

**Comment by FormerLurker** [comment]
@infomagichand, sounds like an upgrade bug when converting the settings.  Perhaps you can help me fix it.  Please export your settings (OctoPrint settings (wrench/spanner icon)->Octolapse->Download settings) file and post it here if you can.  Then you can restore the default settings (OctoPrint settings (wrench/spanner icon)->Octolapse->Restore All Default Settings).  Unfortunately you'll lose your customizations, but things should start working after that.

I hope that helps!

**Comment by FormerLurker** [comment]
This is been idle for a while, so I'm going to go ahead and close this down.  You might be interested to know that Octolapse V0.4 contains support for a new profile repository, allowing you to import/export/download profiles, making it easier to get started, or to share profiles with friends.

Thanks for posting your issue, and feel free to create a new issue if you have any other problems/questions/ideas!
