### ISSUE TITLE
No config menu if Octolapse is Disabled

### ISSUE THREAD

**Issue by andrelec1** [FormerLurker/Octolapse#291]
Octolapse Version: 0.3.4
OctoPrint Version: Octolapse 0.3.4
OctoPrint 1.3.10

Diagnostic Logging was Enabled: NO

#### What were you doing when the problem occurred
Try to add another webcam on octolapse, but not directly related.

#### What should have happened?
Edit settings of octolapse ...

#### What happened instead?
I only have access to the Main and About page in config.

![image](https://user-images.githubusercontent.com/3273204/50044071-bc819900-007e-11e9-8293-3ddda2863d48.png)

![image](https://user-images.githubusercontent.com/3273204/50044091-f2bf1880-007e-11e9-8786-9c137821128c.png)

**Comment by FormerLurker** [comment]
So this should probably change.  It made sense when in an earlier version of the interface, but not at all now.  I'll look into the complexity of the change and will get back with an ETA.

**Comment by FormerLurker** [comment]
So, this has been fixed in V0.4 (still in testing!)  Let me know if you want to try it out.

Closed!
