### ISSUE TITLE
Incorrect Screenshot for Slic3r PE

### ISSUE THREAD

**Issue by larsenv** [FormerLurker/Octolapse#296]
[The screenshot here](https://github.com/FormerLurker/Octolapse/wiki/Printer-Profiles---Slic3r-Prusa-Edition-Settings#perimeter-speed) is incorrect, it shows the retraction speed instead of the other speeds. I see the screenshot in the repo, but it should be fixed.

**Comment by FormerLurker** [comment]
@larsenv, thanks for letting me know.  I should have fixed it immediately, but I was a bit under the weather at the time.  This has been taken care of.

Closed!
