### ISSUE TITLE
Octolapse navbar button

### ISSUE THREAD

**Issue by ssttiijjnn** [FormerLurker/Octolapse#297]
#### Version of Octolapse
Octolapse Version: Octolapse 0.3.4

#### Version of OctoPrint
OctoPrint Version: OctoPrint 1.3.10 running on OctoPi 0.15.1

#### When you ran into the problem, did you have diagnostic logging enabled?
Diagnostic Logging was Enabled: No

#### What were you doing when the problem occurred
OctoPrint was disabled, but still showing the NavBar button. I wanted to disable it. To disable the NavBar button I had to go into settings, enable the plugin, then disable the button in the settings, then disable the plugin again. 

#### What should have happened?
When OctoPrint is disabled the NavBar button should be gone. Or the NavBar button enable disable button in the settings should also be available when the octolapse is disabled.

#### What happened instead?
I had to go into settings, enable the plugin, then disable the button in the settings, then disable the plugin again.  (Because of this it's not a major issue)

#### Operating System running OctoPrint and Octolapse

OS Name: Octopi
Os Version:  0.15.1

**Comment by FormerLurker** [comment]
There are several options within the main settings (octoprint settings->Octolapse->main tab) to control the visibility of the navbar link.  Let me know if those settings work for you.

Thanks for your post!

**Comment by ssttiijjnn** [comment]
I can't find any way to edit the navbar button there.

This is my octoprint settings window
![Main menu](https://user-images.githubusercontent.com/11312685/50641744-47143480-0f69-11e9-8719-1d8c35391ff2.png)

There is no way to enable or disable the navbar button, only a indication if it is enabled or disabled. After opening the settings I only see this
![Octoprint settings](https://user-images.githubusercontent.com/11312685/50641781-6317d600-0f69-11e9-8a5a-0c1f96a549b3.png)

So i first have to enable the plugin to be able to change the navbar button here (last item)
![Settings with plugin enabled](https://user-images.githubusercontent.com/11312685/50641803-72971f00-0f69-11e9-9758-01e1276ef8ac.png)

And change the navbar tab and then disable the plugin again. Maybe i'm missing somthing

**Comment by FormerLurker** [comment]
Set your navbar options within the main settings like so:

![octolapsenavbarcontrols](https://user-images.githubusercontent.com/33363128/50642740-bf5f0380-0f31-11e9-92c0-f11ccbec2421.JPG)

This way the navbar will only show when Octolapse (and a print) is running.

**Comment by ssttiijjnn** [comment]
Thanks, that's nice to have.

The issue was mainly focused towards not being able to change settings when the plugin is disabled. Like i said, it's just a minor inconvenience because you can enable it, change it and disable it. This just feels counter intuitive for me though. But if this is ment to be this way then i understand

**Comment by FormerLurker** [comment]
I've already gotten requests to change the 'disabled' behavior, but haven't gotten around to it yet :)  The next release should have this fixed.  Originally there were issues where users didn't notice they had the plugin disabled, so i wanted to make it more obvious, but I should have just put a big 'disabled' message somewhere instead!

Again, thanks for submitting your issue, and let me know if you have any other questions/requests!

**Comment by FormerLurker** [comment]
@ssttiijjnn, I wanted to let you know that I am adding this feature to the next release (Navbar disabled when Octolapse is disabled).  The current behavior seems very silly now that you pointed this out to me.  Thanks again for your request!

**Comment by FormerLurker** [comment]
@ssttiijjnn, I know this is an old issue, but I've finally gotten around to fixing the enabled/disabled problem you mentioned here.  Now when Octolapse is disabled all settings and tabs remain available, but there are obvious visual indicators showing that Octolapse is disabled.  Here is the main settings screen (which was in your original post:

![image](https://user-images.githubusercontent.com/33363128/66950358-d59c0300-f01d-11e9-865b-ce9b29201832.png)

Here is the tab when disabled:
![image](https://user-images.githubusercontent.com/33363128/66950445-fcf2d000-f01d-11e9-86ef-60a092b3b592.png)

**Comment by FormerLurker** [comment]
Since this issue has been resolved, I'm going to go ahead and close it down.  Thanks for posting!
