### ISSUE TITLE
OctoLapse - Position Error

### ISSUE THREAD

**Issue by Churro1741** [FormerLurker/Octolapse#300]
[Buddy.zip](https://github.com/FormerLurker/Octolapse/files/2735172/Buddy.zip)

#### If this is a feature request describe it here

FEATURE_REQUEST_DESCRIPTION_GOES_HERE

#### Version of Octolapse
 
Octolapse Version: Octolapse 0.3.4

#### Version of OctoPrint

OctoPrint Version: OctoPrint 1.3.10 running on OctoPi 0.15.1

#### When you ran into the problem, did you have diagnostic logging enabled?

Diagnostic Logging was Enabled: YES

#### What were you doing when the problem occurred

1. Set up Octolapse, per FormerLurker guide
2. Set G90 in Printer profile in Cura (before any G/E commands)
3.  Copy unique settings from Cura to Octolapse settings
4. Save and import Gcode to OctoPrint
5. Print Gcode!

#### What should have happened?

Expected a normal print using a webcam to take timelapse photos

#### What happened instead?
After homing, and moving to the first position, Octoprint encounters the following error:

"Octolapse - Position Error
Position - Coordinates (X:174.47000,Y:150.43100,Z:0.25000,E:12.54921) are out of the printer area! Cannot resume position tracking until the axis is homed, or until absolute coordinates are received."

#### Operating System running OctoPrint and Octolapse

OS Name: OctoPi
Os Version: 0.15.1

#### Printer model & used firmware incl. version

Printer Model: Creality CR-10S
Printer Firmware Version: ??  (Marlin, I'm guessing?)

#### Browser and version of browser, operating system running browser

Browser: Chrome
Browser OS: Windows 10 (64 bit)

#### Link to the gcode file you were printing when the problem occurred

Link to Gcode File: Tried using gist.github and encountered error 405 (not allowed)

G.code starts with this:

;FLAVOR:Marlin
;TIME:17971
;Filament used: 14.9286m
;Layer height: 0.2
;POSTPROCESSED
;Generated with Cura_SteamEngine 3.2.1
M190 S75
M104 S210
M109 S210
M82 ;absolute extrusion mode
G90
G28 ;Home
G1 Z15.0 F6000 ;Move the platform down 15mm
;Prime the extruder
G92 E0
G1 F200 E3
G92 E0
;LAYER_COUNT:751
G4 P1M107
M204 S5000
M205 X30 Y30
G0 F3612 X162.385 Y152.318 Z0.25
M204 S500
M205 X20 Y20
;TYPE:SKIRT
G1 F1824 X162.955 Y151.772 E0.03282
.... etc...

#### Link to settings.json

Link to settings.json with all passwords removed: <script src="https://gist.github.com/Churro1741/326ffbbbe4f9b672833083ded7b3c972.js"></script>
#### Link to plugin_octolapse.log

Link to plugin_octolapse.log:  <script src="https://gist.github.com/Churro1741/5f3aba0851ae31d8fa56d4dde609e410.js"></script>

#### Link to octoprint.log

Link to octoprint.log:  <script src="https://gist.github.com/Churro1741/8a6ab1bc3c4f183f45a2f22e067c2433.js"></script>

#### Link to contents of Javascript console in the browser

Link to javascript console output: ??

#### Screenshots and/or videos of the problem:

Screenshot/Video Links: LINKs_GO_HERE
![image](https://user-images.githubusercontent.com/46470560/50809367-ad31ec00-12c8-11e9-889f-877e79a936e0.png)
 Note, I researched for a while and read multiple posts trying to figure this out including issue 144, 131 and others.  Thanks for your help!

## Please consider becoming a patron
If you like this project, [please support my work by becoming a patron,](https://www.patreon.com/bePatron?u=9588101) and consider adding a 'star' to the repository.  It takes a lot of time and effort to maintain the project and respond to issues.  The cost of test prints, software, cameras, printer parts, etc. can quickly add up, so every bit helps.

You can find various [videos and tutorials](https://www.youtube.com/channel/UCnnTLQetNw7FqfQOLJCMqoQ) by subscribing to my Youtube channel.  You can also [follow me on Twitter](https://twitter.com/FormerLurker1).

**Comment by FormerLurker** [comment]
@Churro1741, I am so sorry but I missed this post somehow :(  I'll run your code through the debugger a bit later today and will get back to you.  Thank you so much for providing (I think) everything I need to debug the problem!

**Comment by FormerLurker** [comment]
Ok, it looks like your printer volume is incorrect.  Change your y-max to 300.  That will probably solve your issue.

I'm not 100% sure exactly what your volume is, btw, I just guessed based on the advertised volume, but it's not too hard to discover if you are willing to run a few gcodes (and probably skip your steppers just a bit).  You can manually send few commands through the terminal in Octoprint to do this.

First a `G28` should home your printer.
Then you can try a `G0 X0 Y0` followed by an M114.  Does your printer say you are at 0,0 (probably yes)?

From there you can send more G0 commands to test the bounds of your printer, like
```
G0 X300 Y0
M114
````

The M114 command should return the X and Y coordinates you sent.  If it doesn't, your printer probably prevented the axis from moving too far out of bounds.  if any steppers skip here 300 is too far.  if not, repeat the above but with X301, X302, etc... until it does skip or hits the endstop, or doesn't move any more.  Warning:  If your stepper skips you'll need to execute another G28 to continue testing else your results will be off.

Then repeat for each axis, both min and max.  Let me know if you need any assistance.

**Comment by FormerLurker** [comment]
HI there!  I just noticed I failed to close this issue, though we got the problem solved like 9 months ago!  Anyway, thanks for posting, and closed!
