### ISSUE TITLE
Octolapse erases the warmup GCode

### ISSUE THREAD

**Issue by Zylvian** [FormerLurker/Octolapse#302]
Everything up to date 08.01.2019.

Whenever I try to run a print with Octolapse, the print will start without warming up the nozzle. One time I didn't realize this and it skipped for two minutes and grinded the filament before I could stop it. Has not had any change after multiple restarts of the OctoPi.

Slicer: Cura
Printer: Ender 3
RPi: 3B+

**Comment by FormerLurker** [comment]
You probably have 'Test Mode' enabled.  Look at the 'Debug' profile selection in the Octolapse tab (or in the OctoPrint Settings->Octoprint->Debug window).  

Test mode is designed to make it fast and easy to test your Octolapse settings.  It prevents warmup, fan operations and extrusion (among a few other things).

Let me know if that helps!

**Comment by FormerLurker** [comment]
@Zylvian,

This looks like a different problem.  Try editing your octolapse printer profile and set 'X/Y/Z Axis Mode' to 'Default To Absolute', save the changes, then try again.  Let me know if that fixes your problem!

**Comment by FormerLurker** [comment]
@Zylvian, did my last suggestion help at all?

**Comment by FormerLurker** [comment]
I'm going to close issue since I suspect your problem is either solved or no longer applicable.  Please let me know if you'd like it reopened, and thanks for posting!!!
