### ISSUE TITLE
can't install octolapse

### ISSUE THREAD

**Issue by DrMarkyMarc** [FormerLurker/Octolapse#321]
#### If this is a feature request describe it here

FEATURE_REQUEST_DESCRIPTION_GOES_HERE

#### Version of Octolapse
 
Octolapse Version: 1.3.9+

#### Version of OctoPrint

OctoPrint Version: 1.3.10

#### When you ran into the problem, did you have diagnostic logging enabled?

Diagnostic Logging was Enabled: YES

#### What were you doing when the problem occurred

1. Try to install octolapse
2. via octopi
3. via octoprint
4. updated and upgraded everything I could 
5. googling and installing all the pillow library recomanded to make this work (no succes)

#### What should have happened?
install octolapse. 

#### What happened instead?
it gave me an error and then the green pop up sayd install but instead of having octolapse in the pop up it sayd nothing installed

#### Operating System running OctoPrint and Octolapse

OS Name: Linux octopi
Os Version: 4.14.79-v7+

#### Printer model & used firmware incl. version

Printer Model: Prusa mk3 i3
Printer Firmware Version: PRINTER_FIRMWARE_VERSION_GOES_HERE

#### Browser and version of browser, operating system running browser

Browser: Chrome
Browser OS: BROWSER_OS_GOES_HERE

#### Link to the gcode file you were printing when the problem occurred

Link to Gcode File: GCODE_FILE_LINK_GOES_HERE

#### Link to settings.json

Link to settings.json with all passwords removed: SETTINGS_JSON_LINK_GOES_HERE

#### Link to plugin_octolapse.log

Link to plugin_octolapse.log: https://pastebin.com/BBcyPEQJ

#### Link to octoprint.log

Link to octoprint.log:  LINK_GOES_HERE

#### Link to contents of Javascript console in the browser

Link to javascript console output: https://pastebin.com/BBcyPEQJ

#### Screenshots and/or videos of the problem:

Screenshot/Video Links: LINKs_GO_HERE

## Please consider becoming a patron
If you like this project, [please support my work by becoming a patron,](https://www.patreon.com/bePatron?u=9588101) and consider adding a 'star' to the repository.  It takes a lot of time and effort to maintain the project and respond to issues.  The cost of test prints, software, cameras, printer parts, etc. can quickly add up, so every bit helps.

You can find various [videos and tutorials](https://www.youtube.com/channel/UCnnTLQetNw7FqfQOLJCMqoQ) by subscribing to my Youtube channel.  You can also [follow me on Twitter](https://twitter.com/FormerLurker1).

**Comment by FormerLurker** [comment]
It took me like 30 sec to scroll through that to reply, lol!  Maybe post a link next time instead?

So when you said you tried installing pillow, what happened?  Did you install it into the octoprint virtual environment?  If so, what errors did you receive?

So ive seen issues with pillow before, and the solution is usually either upgrading pip like this:

source home/pi/oprint/bin/activate

Then

pip install --upgrade pip


Then reinstalling.

The other issue was really difficult to figure out.  Pillow apparently fails if your psu is not powerful enough.  I had a hard time believing that at first, but ive seen it several times now.  Check out [this](https://github.com/FormerLurker/Octolapse/issues/234) closed issue.

**Comment by DrMarkyMarc** [comment]
**well i got this from what you ask me to do**
Requirement already up-to-date: pip in /home/pi/.local/lib/python2.7/site-packag                         es (19.0.2)

**if i try to install it via console**  ended up with this
`Could not import OctoPrint's setuptools, are you sure you are running that under the same python installation that OctoPrint is installed under?`
`Command python setup.py egg_info failed with error code 255 in /tmp/pip-64i4ibgi-build`

**So i figure I mith not have the good python so I did this**
/home/pi/oprint/bin/python -m pip install "https://github.com/FormerLurker/Octolapse/archive/v0.3.4.zip"

**and it get stuck till I Ctrl+c** 
It just freeze withing 2 second of running that command when it get to this line (the thing that usualy turn even stop turning)

building wheel for pillow setup.py 

Iv waited for 30 min nothing happend Ctrl+c work

**Comment by FormerLurker** [comment]
Can you post your console output where you try to install Pillow via the command line, including the lines where you activate the virtual environment?

However, the error you are seeing trying to install pillow is probably related to your power supply.  Double (triple) check that your PSU is powerful enough to run your pi.  This causes all kinds of insane issues.  Octoprint has a feature to detect undervoltage if you're running the latest version.  Not sure if you read the previous thread on this issue, but [here is is again](https://github.com/FormerLurker/Octolapse/issues/234) in case you haven't.

**Comment by DrMarkyMarc** [comment]
i'm powering my rpi via my 3d printer board via gpio pin I will look how much power it give but I do not see a not enouff power logo in octoprint

**Comment by FormerLurker** [comment]
Can you post all console output for when you are trying to install pillow via the command line please, include everything after you sign in.  Thanks!

**Comment by wtfdic** [comment]
Having a very similar issue. Went through everything in the other thread about PSU and got pretty far now I am facing this error when installing Octolapse:

Command "/home/pi/oprint/bin/python2 -u -c "import setuptools, tokenize;__file__='/tmp/pip-install-ETznR_/pillow/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-record-Vv0saC/install-record.txt --single-version-externally-managed --compile --install-headers /home/pi/oprint/include/site/python2.7/pillow" failed with error code 1 in /tmp/pip-install-ETznR_/pillow/
Error!
Could not parse output from pip, see plugin_pluginmanager_console.log for generated output

**Comment by FormerLurker** [comment]
@wtfdic, have you updated pip or tried installing pillow manually?  There are instructions above.  Let me know if you need help.

**Comment by wtfdic** [comment]
@FormerLurker got it working here are the steps that worked for me:

source oprint/bin/activate
sudo apt-get update
sudo apt-get upgrade
sudo apt-get dist-upgrade
sudo apt-get install python-dev
pip install --upgrade pip
sudo apt-get install libjpeg62
sudo apt-get install libjpeg62-dev
sudo apt-get install zlib1g-dev
sudo apt-get install libfreetype6-dev
sudo apt-get install liblcms1-dev
sudo apt-get install libopenjp2-7
sudo apt-get install libtiff5
sudo apt-get install ffmpeg
sudo apt-get install libjpeg8-dev
pip install pillow

then install octolapse from plugin manager

**Comment by FormerLurker** [comment]
@wtfdic, are you running the latest octopi image?  Glad you got it working!

**Comment by wtfdic** [comment]
@FormerLurker yes running 0.16.0 on a Raspberry Pi 3 A+

**Comment by FormerLurker** [comment]
I'm really confused as to why Pillow seems to install fine for some people on the newest OctoPi, but not for others.  If it's not PSU related, perhaps some other version of libjpeg62-dev was installed previously before your PSU issues were sorted out?  In any case, since we probably can't replicate the issue anymore (it works for me with a fresh install), I'm going to close this issue.  I really wish Pillow would give me fewer install problems, but it is free and extremely useful, so I won't complain too much :)

Let me know if you think I should reopen this issue for any reason.
