### ISSUE TITLE
Make GCode parsing case-insensitive

### ISSUE THREAD

**Issue by Shadowen** [FormerLurker/Octolapse#33]
Some places in the code are still case-sensitive. I know the parsing front-end is mostly proof against this, but some of the internals will crash if provided a lowercase GCode (one of the tests is failing because of this :( ).

Low priority unless a user-affecting issue is discovered.

> The original NIST GCode standard requires gcode interpreters to be case-insensitive, except for characters in comments. However, not all 3D printer firmwares conform to this and some recognise uppercase command letters and parameters only.

**Comment by FormerLurker** [comment]
I'll review command.py and see what I can find.  Let me know the nature of the failed test and I'll pay extra attention to that.

**Comment by Shadowen** [comment]
test_trigger_gcode.py was sending `g28` rather than `G28`. I'm pretty sure that was causing a problem, but I've got bigger problems to fix before it passes.

**Comment by Shadowen** [comment]
Let's not worry about this until it's a real issue.
