### ISSUE TITLE
[Request] adding "Failed Snapshot Count: " to bottom of octolapse

### ISSUE THREAD

**Issue by MineThingIssues** [FormerLurker/Octolapse#337]
#### If this is a feature request describe it here
It would be quite helpful for debugging purposes to have a count of all the failed snapshots, and if possible a sort of graph that could be used to find the frequency of failures (The graph could be snapshots going horizontally with a green line above for success  and a red line above for failure. Similar to this: 
![image](https://user-images.githubusercontent.com/47724587/56064305-a1dbda00-5d69-11e9-8c27-54494f29f8fd.png)
 but with green instead of white and red instead of blue). It is a little thing but I think that it could be a useful tool for debugging (such as trying out different timeout settings to see how that affects the reliability of snapshots)

#### Version of Octolapse
 
Octolapse Version: 0.3.4

#### Version of OctoPrint

OctoPrint Version: 1.3.10

**Comment by FormerLurker** [comment]
Interesting idea.  I was thinking of adding some debugging screens that would include things like position errors, gcode errors, warnings and other useful info, but I don't think I can fit this on the current tab without some design changes.  Eventually I also want to add setup and debugging tools like automatic printer setup too, which might also work well on such a screen.  However, a failed snapshot count could pretty easily fit on the existing tab, though I think the graph would work better in a different view.  Ideas?

I think the next step is just to sketch this out and try to flush out what works.

**Comment by FormerLurker** [comment]
Update (after months...):  Still working on this.  I may yet include this in the next version of octolapse.  Will keep you posted.

**Comment by FormerLurker** [comment]
This feature is now available in the latest devel/rc and devel branches.  Let me know if you want to try it out.  The number of snapshot errors (failed snapshots) now displays IF there is at least one error.  If you try it and have problems, please post on [this thread.](https://github.com/FormerLurker/Octolapse/issues/455) 

Closed at long last!
