### ISSUE TITLE
Octoprint FlipCam 90° not for snapshots ?

### ISSUE THREAD

**Issue by tardar** [FormerLurker/Octolapse#351]
Octolapse Version: -
OctoPrint Version: 1.13.11

Diagnostic Logging was Enabled: NO

#### What were you doing when the problem occurred

1. Configured FlipCam to 90°
2. Print
3. Make a snapshot and it wasn't flipped

#### What should have happened?
The Snapshot should been flipped like the live Cam video.

#### What happened instead?
The liveCam Picture wasnÄt flipped and looks bad on mky smartphone ^^

OctoPi, Linux
OS Name: OctoPi
Os Version: 0.16.0

**Comment by FormerLurker** [comment]
Look in your octolapse camera profile at the transpose setting.  You can rotate/flip/invert there

**Comment by FormerLurker** [comment]
Did that do the trick for you?

**Comment by tardar** [comment]
No it didn't.
I flipped the cam in OctoPrint so i can see the right webcam picture.
Now i try to send via FHEM a picture to my smartphone and it uses the Link from the webcam (snapshot).

I think i have to manipulate the link (with a parameter) to flip the picture.
Any ideas ? :)

Thanks really alot

**Comment by FormerLurker** [comment]
Wait, are you talking about the snapshot url, and you are using that with fehm?  So really this has nothing to do with octoprint or octolapse.  The software running the camera stream is called mjpegstreamer.  It is installed by default on OctoPi.  I think it is possible to tell mjpegstreamer to pre rotate your stream for the pi cam, but I don't think it is possible for usb cameras (I could easily be wrong).  In any case there is no way to rotate the video via a url.  You could also create a script on your pi to rotate the image, or if you are using octolapse, you can download the latest snapshot via a url.  It wont be real time, of course.  Let me know if you'd like to try that.

You could also install a different streaming server that supports rotation.  Shouldn't be hard.  Better yet, install it on a second pi and offload all that workload!

**Comment by FormerLurker** [comment]
Were you ever able to get this working?  Since I'm pretty sure this isn't an Octolapse issue at all, I'm going to go ahead and close the ticket.  If you have any more questions, just let me know and I'll reopen it.

Thanks for posting!
