### ISSUE TITLE
Breaking vase mode with default setting is not acceptable.

### ISSUE THREAD

**Issue by mantafloppy** [FormerLurker/Octolapse#352]
#### If this is a feature request describe it here

Breaking vase mode with default setting is not acceptable.

#### Version of Octolapse
 
Octolapse Version: Octolapse 1.3.10

#### Version of OctoPrint

OctoPrint Version: Octolapse 0.3.4

#### When you ran into the problem, did you have diagnostic logging enabled?

Diagnostic Logging was Enabled: No idea

#### What were you doing when the problem occurred

Using it normally.

#### What should have happened?
Not break vase mode print.

#### What happened instead?
Break the vase mode print.

#### Operating System running OctoPrint and Octolapse

OS Name: octopi
Os Version: 0.16.0

#### Printer model & used firmware incl. version

Printer Model: prusa mk3s
Printer Firmware Version: 3.7.1

#### Link to the gcode file you were printing when the problem occurred

Link to Gcode File: 

#### Link to settings.json

Link to settings.json with all passwords removed: SETTINGS_JSON_LINK_GOES_HERE

#### Link to plugin_octolapse.log

Link to plugin_octolapse.log:  LINK_GOES_HERE

#### Link to octoprint.log

Link to octoprint.log:  LINK_GOES_HERE

#### Link to contents of Javascript console in the browser

Link to javascript console output: LINK_GOES_HERE

#### Screenshots and/or videos of the problem:

Screenshot/Video Links: https://i.imgur.com/iLutyn4.mp4

## Please consider becoming a patron
If you like this project, [please support my work by becoming a patron,](https://www.patreon.com/bePatron?u=9588101) and consider adding a 'star' to the repository.  It takes a lot of time and effort to maintain the project and respond to issues.  The cost of test prints, software, cameras, printer parts, etc. can quickly add up, so every bit helps.

You can find various [videos and tutorials](https://www.youtube.com/channel/UCnnTLQetNw7FqfQOLJCMqoQ) by subscribing to my Youtube channel.  You can also [follow me on Twitter](https://twitter.com/FormerLurker1).

**Comment by FormerLurker** [comment]
I've fixed this in the development version by setting a (configurable) minimum layer height of 0.01mm.  However, there are 'height' options in the layer trigger settings to handle this already.  Just set it to your layer height and you should be good.

Also, you'll have quality issues printing in vase mode in the current master version in almost all cases (especially if you've not tweaked any of the settings).  I have a new stabilization that works pretty well in the development release for vase mode.  See [this](https://www.youtube.com/watch?v=wKCEkV0ISG8&t=1113s) video for details.  It jumps to a video of the new stabilization, but there is more info a bit earlier if you care about that.
