### ISSUE TITLE
Fails to start because the delay from Android app IP Web Cam

### ISSUE THREAD

**Issue by mattbruman** [FormerLurker/Octolapse#354]
I am using IP Webcam on android phone and because it takes a few seconds to take the snapshot octolapse says it fails. If I hit test it actually is successful every 3-4 times I hit test. Are logs needed? I think if we can just add a longer delay before it says it failed it would solve the issue, I have tried setting the timeout to the max but it still says failed.

Or maybe there is a better app to use on android that plays better with octolapse?

**Comment by FormerLurker** [comment]
Check the time out setting in the camera profile.  That should solve your problem.

**Comment by mattbruman** [comment]
I said I set it to the max but it still errors, its weird, because I can hit take snapshot in the web interface for the app and it pops up but for some reason octolapse says it fails.

**Comment by FormerLurker** [comment]
Hmm.  Can you tell me what the error message says exactly?  Also, export your settings file (octoprint setting->Octolapse->export settings), and attach it?  Don't post it if your camera has a password, it will be in the settings file.  I need to deal with that soon.

**Comment by FormerLurker** [comment]
Did you ever get this figured out?  I'm going to close the ticket for now, and will re-open it if you need more help, so just let me know!

Thanks for posting!
