### ISSUE TITLE
Minor issue with 

### ISSUE THREAD

**Issue by leoheck** [FormerLurker/Octolapse#358]
Speed and Features text issue, using Octolapse version `0.3.4` and Octoprint `1.3.11`
![image](https://user-images.githubusercontent.com/1277920/59968916-85ea7680-9518-11e9-8f69-258286aed78f.png)

**Comment by FormerLurker** [comment]
This might have already been fixed in the dev branch.  When I have a chance to check I'll post back.

**Comment by leoheck** [comment]
Ah, that is cool, thanks for the answer.

**Comment by FormerLurker** [comment]
So, feature detection works differently now.  I"m no longer using speed based detection, and it's all handled via preprocessing.  Feature detection has been completely removed when using the real time triggers (all triggers in 0.3.4).  

Here is a screen shot

![image](https://user-images.githubusercontent.com/33363128/66942589-0a548e00-f00f-11e9-9105-eccb840ba94d.png)


Feature detection is now based on gcode file comments, and only works with the new Smart Layer triggers (v0.4).  If the proper comments are available in the gocde file, feature detection automatically works.  If they are not there the user is warned of possible quality ramifications (not a popup).  Here is a screenshot of that:

![image](https://user-images.githubusercontent.com/33363128/66942680-37a13c00-f00f-11e9-8ea7-95dab34f3f15.png)

Note that clicking on the question mark above opens help that details how to deal with these quality issues:

![image](https://user-images.githubusercontent.com/33363128/66942722-4c7dcf80-f00f-11e9-9a71-a5bcfed2dda8.png)

I know that involves more than the issue you reported, but I wanted to include the full story.

**Comment by FormerLurker** [comment]
I've confirmed that the bug you reported is fixed, so I'm calling this CLOSED!  Thanks for the report!
