### ISSUE TITLE
Camera Rotation

### ISSUE THREAD

**Issue by DerNeuanfang** [FormerLurker/Octolapse#374]
I use Raspi-Cam with Octolaps.
On Preview ("Control") is the Camera Stream Flippet (Settings from Octoprint), thats is rigth.

On Octolaps the Picture is flipped (it is up side down).
Dont find Settings to flipped it (180°).

What can i do?

**Comment by FormerLurker** [comment]
@DerNeuanfang, any update on this issue?  I'm marking it as waiting for response, and will consider it closed if I don't hear back from you.  Thanks your posting your issue!!!

**Comment by FormerLurker** [comment]
So, it's been over 30 days, so I'm going to go ahead and close this issue.  Message me if you'd like it reopened.  Thanks!
