### ISSUE TITLE
Cura 4.2.1 slicing & 0.4.0rc1.d2

### ISSUE THREAD

**Issue by monkeyprolabs** [FormerLurker/Octolapse#385]
Ok...followed the guides to get 0.4.0rc1.d2 installed and working. Had success on the install, but could not get it to run with my slicer, Cura 4.2.1. After pasting the revised start gcode into my machine's settings and reslicing, I get this error when I try to print it: _"Octolapse Startup Failed Unable to start the timelapse. Cancelling print. Error: Unable to start the print. Some required slicer settings are missing or corrupt: Retract Before Move,Lift When Retracted"_

[here](https://gist.github.com/monkeyprolabs/6c9f4b2ab63c5e08c58cbb26d24f3aca) is my gcode

[here](https://gist.github.com/monkeyprolabs/08cab87277d9914889d1f81c464c4510) are my octolapse settings

here is what my machine start gcode looks like:

; Script based on an original created by tjjfvi (https://github.com/tjjfvi)
; An up-to-date version of the tjjfvi's original script can be found
; here: https://csi.t6.fyi/
; Note - This script will only work in Cura V4.2 and above!
; speed_z_hop = {speed_z_hop}
; retraction_amount = {retraction_amount}
; retraction_hop = {retraction_hop}
; retraction_hop_enabled = {retraction_hop_enabled}
; retraction_prime_speed = {retraction_prime_speed}
; retraction_retract_speed = {retraction_retract_speed}
; retraction_speed = {retraction_speed}
; speed_travel = {speed_travel}
; retraction_enable = {retraction_enable}
; layer_height = {layer_height}
; smooth_spiralized_contours = {smooth_spiralized_contours}
; magic_mesh_surface_mode = {magic_mesh_surface_mode}

G28 ;Home
G90 ; use absolute coordinates
M84 ; use absolute distances for extrusion
G92 E0 ; zero the extruded length
G1 X40 E25 F500 ; Extrude 25mm of filament in a 4cm line
G92 E0 ; zero the extruded length
G1 E-1 F500 ; Retract a little
G1 X80 F4000 ; Quickly wipe away from the filament line
G1 Z0.3 ; Raise and begin printing.

**Comment by FormerLurker** [comment]
Fortunately the fix is simple.  Switch your 'Slicer Type' in your printer profile to 'Automatic Configuration' and you should be set!  It worked fine for me, so it should for you too.  Let me know if it helps!

**Comment by monkeyprolabs** [comment]
worked perfectly!  gah!  i can't believe it was that easy!  (thank you)

**Comment by FormerLurker** [comment]
Excellent :)  Closed!

**Comment by EJtechandDiy** [comment]
[octoprint.log](https://github.com/FormerLurker/Octolapse/files/3736208/octoprint.log)

 Hi Lurker

Im also trying 0.4.0rc1.d2 with Simplify3D,I try your fix by changing to 'Automatic Configuration' but I keep getting the same error "Octolapse Startup Failed Unable to start the timelapse. Cancelling print. Error: Unable to start Unable to start the timelapse''.

Let me know if you need more info.

thank you for your time

**Comment by FormerLurker** [comment]
@EJtechandDiy, can you create a new issue for this?  Also, try installing from this link in the plugin manager, as there have been several fixes:  https://github.com/FormerLurker/Octolapse/archive/devel.zip

Note that that link is in flux, but won't change for the next 24 hours.

Once it is installed, click the gear icon on the Octolapse tab to open the main settings, and click 'Export Settings' to save a copy of your current settings (you can import them again later) and then click 'restore defaults'.  That will erase your settings completely, but it should be easy to setup again.

Once you've added a new printer profile (see if your printer exists in the make/model drop down, which should make that part easy), switch your debug profile to 'Test Mode - Debug Issues'.  Then run a small print and see if it errors out.  If it does, be sure to attach (via gist.github.com) your plugin_octolapse.log, which should contain some detailed error information.

Let me know how it goes in the new issue!

**Comment by EJtechandDiy** [comment]
Sure thing I will make a new one, my apologies I did not pay attention to the big red CLOSED icon.
