### ISSUE TITLE
[request] Add Test Mode Warning Message

### ISSUE THREAD

**Issue by mooklepticon** [FormerLurker/Octolapse#390]
#### If this is a feature request describe it here

Please add a warning message that test mode doesn't extrude filament. 

lol, I just spent the last hour troubleshooting octoprint thinking it was that. I had octolapse in test mode. Yes, I realize I'm a moron, but there are dozens of us, DOZENS.

#### Version of Octolapse
Octolapse Version: Octolapse 0.3.4

#### Version of OctoPrint

OctoPrint Version: OctoPrint 1.3.11 running on OctoPi 0.16.0

**Comment by FormerLurker** [comment]
Lol!  Ok, I will see what I can do.

**Comment by FormerLurker** [comment]
How does this look:

![image](https://user-images.githubusercontent.com/33363128/66840424-a1e1b000-ef2d-11e9-9b38-6395e3f2bf17.png)

**Comment by mooklepticon** [comment]
I think that's great!

**Comment by FormerLurker** [comment]
Excellent!  I also added tooltips to show the profile descriptions, both for the selected option, and the options list when you click on the dropdowns.  That should help too, since I can add a much more detailed description within the profile itself.

Closed!
