### ISSUE TITLE
Printer Not Supported - M114

### ISSUE THREAD

**Issue by SamKemp** [FormerLurker/Octolapse#463]
#### Version of Octolapse
 
Octolapse Version: v0.4.0rc1.dev4

#### Version of OctoPrint

OctoPrint Version: 1.4.0rc6

#### When you ran into the problem, did you have diagnostic logging enabled?

Diagnostic Logging was Enabled: No

#### What were you doing when the problem occurred

1. Installed OctoLapse plugin
2. Setup Octolapse for my printer... setting Printer, Stabilization, etc
3. Clicked Print

#### What should have happened?
Print should of started

#### What happened instead?
Error, Printer not supported
![image](https://user-images.githubusercontent.com/4368702/75440322-7d71f780-5953-11ea-8317-9aae0ded2f94.png)

#### Operating System running OctoPrint and Octolapse

OS Name: Linux, Raspbin
Os Version: OS_VERSION_GOES_HERE

#### Printer model & used firmware incl. version

Printer Model: Creality - Ender 3 Pro
Printer Firmware Version: Marlin 2.0.3_C 

#### Link to the gcode file you were printing when the problem occurred

Link to Gcode File: [CE3_RING_OCTOLAPSE.gcode.txt](https://github.com/FormerLurker/Octolapse/files/4261339/CE3_RING_OCTOLAPSE.gcode.txt)

#### Link to settings.json

Link to settings.json with all passwords removed: [settings.json.txt](https://github.com/FormerLurker/Octolapse/files/4261345/settings.json.txt)

#### Link to plugin_octolapse.log

Link to plugin_octolapse.log:  [plugin_octolapse.log](https://github.com/FormerLurker/Octolapse/files/4261348/plugin_octolapse.log)

#### Link to octoprint.log

Link to octoprint.log:  [octoprint.log](https://github.com/FormerLurker/Octolapse/files/4261351/octoprint.log)

#### Screenshots and/or videos of the problem:

Screenshot/Video Links: 
![image](https://user-images.githubusercontent.com/4368702/75441275-456bb400-5955-11ea-89c8-d9e730636d47.png)
![image](https://user-images.githubusercontent.com/4368702/75441308-59afb100-5955-11ea-9169-18a9f3df6eda.png)

**Comment by FormerLurker** [comment]
Can you try installing from the devel branch, i may have fixed this already.

**Comment by SamKemp** [comment]
That seems to have worked... I have only just started my first print after updating

I did have an issue prior regarding Octolapse not saving my timelapse, I had reinstalled Octolapse to try and solve that issue and thats when I came across this M114 error. Will let you know how both these issues pan out

**Comment by SamKemp** [comment]
Thank you so much for the help. My Octolapse is working great now.

No worries on the Dropbox plugin, my flatmate saw the plugin and wanted it to work with Octolapse so I made my quick and dirty fork but its great that we have a good solution

**Comment by FormerLurker** [comment]
Fantastic!  I will push a new rc this weekend.

Have your flatmate respond to the Dropbox plugin issue.  I am guessing he/she was the OP?

**Comment by SamKemp** [comment]
No, my flatmate is @TWIISTED-SHOPS , I had asked him to test your version

**Comment by FormerLurker** [comment]
Ok, great!  Tell him I said hi and thanks!
