### ISSUE TITLE
Tinycam pro

### ISSUE THREAD

**Issue by lordstryfe** [FormerLurker/Octolapse#479]
I am using tinycam pro on an android device to stream my wyzecam. I can see the stream just fine in the normal octoprint timelapse setting. Yet no matter what I so I cannot get octolapse to pull an image no matter what settings I put in. 

Any hwlpl would be great.

**Comment by FormerLurker** [comment]
What snapshot url are you using in octoprint vs octolapse?  Please fill in the issue template next time you post.  Otherwise my first few responses will probably be to ask for information that was in the template.

**Comment by FormerLurker** [comment]
I'm going to assume you figured this out.  If you want me to reopen the issue, fill in the template and I'd be happy to reopen it.  Thanks for posting!
