### ISSUE TITLE
Add units to number input fields

### ISSUE THREAD

**Issue by nbun** [FormerLurker/Octolapse#5]
Especially the printer configuration page has many number input fields like retraction length that need a unit to make sense. The Octoprint printer configuration page has input boxes with units, so I assume these could be used here?

**Comment by FormerLurker** [comment]
That's a good idea.  I'll mimic the Octoprint styles.  Marking as enhancement.  I'll add soon and will commit the changes.

**Comment by FormerLurker** [comment]
Ok, I've added units to the menu options where it seemed appropriate.  I also re-arranged and re-worded a bit.  I'm open to suggestions if you see any settings that are confusing, or could use better names/descriptions.

I'll leave the issue open.

**Comment by FormerLurker** [comment]
I'm going to go ahead and close this.  If you think other menu items should be renamed/made clearer, or if you notice any missing/buggy validations, please open a new ticket.
