### ISSUE TITLE
Enable Preferences Custom Image Error

### ISSUE THREAD

**Issue by frozenk33** [FormerLurker/Octolapse#510]
Hi, i have a error when i want enable and apply préferences before print on octolapse, i used Picam 
erreur : `webcam_settings_apply_error: An unexpected error was raised while testing custom image preferences for the 'Default Webcam' camera profile. - Inner Exception: ('Connection aborted.', BadStatusLine('No status line received - the server has closed the connection',))`

( sorry for my bad english :) )

![image](https://user-images.githubusercontent.com/64584850/80696559-d850d800-8ad7-11ea-897a-8477b5d22072.png)

**Comment by FormerLurker** [comment]
You need to use Octolapse V0.4.0rc1 ([see this guide](https://github.com/FormerLurker/Octolapse/wiki/V0.4-Getting-Started-with-Octolapse)), then use [this guide](https://github.com/FormerLurker/Octolapse/wiki/Configuring-a-Raspberry-Pi-Camera) to enable image preferences for the picam.  Good luck!
