### ISSUE TITLE
Octolapse rendering fails

### ISSUE THREAD

**Issue by mikeapmap** [FormerLurker/Octolapse#529]
Running octoprint 1.4.0 - octolapse 0.3.4
Rendering fails to find libavdevice.so.55, but on my pi it's ./usr/lib/arm-linux-gnueabihf/libavdevice.so.58
ffmpeg version (7:4.1.4-1+rpt1~deb10u1).

**Comment by FormerLurker** [comment]
Does ffmpeg work in the stock octoprint timelapse?

**Comment by mikeapmap** [comment]
Operator error; I had the path to ffmpeg pointing to an old avconv. Once I replaced the path to ffmpeg all is working fine. Sorry for the raising the issue

**Comment by FormerLurker** [comment]
Not a problem!  There are a lot of settings to keep straight.  Glad you got it working 👍
