### ISSUE TITLE
PLUGIN_OCTOLAPSE_MOVIE_DONE not firing event

### ISSUE THREAD

**Issue by AJErazzor** [FormerLurker/Octolapse#543]
#### Version of Octolapse
 
Octolapse Version: 0.4.0

#### Version of OctoPrint

OctoPrint Version: 1.4.0

trying to get PLUGIN_OCTOLAPSE_MOVIE_DONE event to fire after an octolapse is complete.  Tried both upper and lower case - is it in this final 0.4.0 version?

config.yaml:
events:
    enabled: true
    subscriptions:
    -   command: 'youtube-upload --client-secrets= "/home/pi/youtube-upload-credentials.json"
            --title="Timelapse: {gcode}" --description="Timelapse of {gcode}, printed
            and recorded via OctoPrint" --category="Science & Technology" --tags=OctoPrint
            "{movie}"'
        event: plugin_octolapse_movie_done
        type: system

**Comment by FormerLurker** [comment]
Yes.  It is integrated with the dropbox  upload plugin, so I know it cant work.  I haven't used the YouTube upload plugin though.  Does it work with the stock timelapse plug-in if you use the octoprint movie done event?

**Comment by AJErazzor** [comment]
Can’t work or can work?

Thanks
Andrew

**Comment by FormerLurker** [comment]
I edited the post, sorry am on mobile.  Yes, the event does fire in 0.4, unless there is some undiscovered bug.  I tgink you can log octoprint events to verify, but I will add some logging to Octolapse for further verification.  Will let you know when that is done.

**Comment by AJErazzor** [comment]
hi thanks for the tip i thoght everylogging option was on but can see the different types - it is working with plugin_octolapse_movie_done beautifully combines with the youtube-upload script
