### ISSUE TITLE
Disable  "Accept Continue?" dialog when starting print

### ISSUE THREAD

**Issue by TwatBurglar** [FormerLurker/Octolapse#574]
Is there a way to disable the "Accept and Continue" prompt when starting a print?   I do not like clicking buttons.

**Comment by FormerLurker** [comment]
Yes, check the main settings

**Comment by TwatBurglar** [comment]
Thanks dude!   Evidently not enough coffee today....

**Comment by FormerLurker** [comment]
No problem!  Enjoy
