### ISSUE TITLE
Octolapse 4 cancels capture but allows print to continue says it is expecting an explicit G21

### ISSUE THREAD

**Issue by sr1329** [FormerLurker/Octolapse#578]
#### If this is a feature request describe it here

___REPLACE_THIS__FEATURE_REQUEST_DESCRIPTION_GOES_HERE

#### Version of Octolapse
 
 4.0

#### Version of OctoPrint
 
OctoPrint Version: 1.4.2

#### When you ran into the problem, did you have diagnostic logging enabled?

Diagnostic Logging was Enabled: NO

#### What were you doing when the problem occurred

1.  Configuration is Ender 3 profile
2.  Started a print
3.  Error appeared as a notification stating that Octolapse is expecting an M21 code. The print will continue but Octolapse will not. 
4. Added M21 to start code
5. Same error upon attempting a print
6. Checked settings and found the dropbox to change from requiring G21 explicitly to assuming millimeters without a G21
7. Same error upon attempting a print

#### What should have happened?
Octolapse should have accepted the G21 code in the start code or not required an explicit G21 when set to assume millimeters.

#### What happened instead?
Octolapse cancelled its operations and allowed the print to continue

#### Operating System running OctoPrint and Octolapse

OS Name: OctoPi 18.1 beta
Os Version: 18.1

#### Printer model & used firmware incl. version

Printer Model: Ender 3 V2
Printer Firmware Version: Marlin 2.0.6 

#### Browser and version of browser, operating system running browser

Browser: Firefox 79 and Microsoft Edge  84.0.522.58
Browser OS: Windows 10 Version 2004

#### Link to the gcode file you were printing when the problem occurred

Link to Gcode File: https://www.dropbox.com/s/y15faghpnztf152/FULL-TOP_40MM_SLOTTED.gcode?dl=0

#### Link to settings.json

Link to settings.json with all passwords removed: https://www.dropbox.com/s/y15faghpnztf152/FULL-TOP_40MM_SLOTTED.gcode?dl=0

#### Link to plugin_octolapse.log

Link to plugin_octolapse.log:  https://www.dropbox.com/s/e0qjiqnnhkqqo64/plugin_octolapse.log.2020-08-11?dl=0

#### Link to octoprint.log

Link to octoprint.log: https://www.dropbox.com/s/9z33302lesqcztd/octoprint.log.2020-08-11?dl=0

#### Link to contents of Javascript console in the browser

Link to javascript console output: ___REPLACE_THIS__LINK_GOES_HERE

#### Screenshots and/or videos of the problem:

Screenshot/Video Links: ___REPLACE_THIS__LINKs_GO_HERE

## Please consider becoming a patron
If you like this project, [please support my work by becoming a patron,](https://www.patreon.com/bePatron?u=9588101) and consider adding a 'star' to the repository.  It takes a lot of time and effort to maintain the project and respond to issues.  The cost of test prints, software, cameras, printer parts, etc. can quickly add up, so every bit helps.

You can find various [videos and tutorials](https://www.youtube.com/channel/UCnnTLQetNw7FqfQOLJCMqoQ) by subscribing to my Youtube channel.  You can also [follow me on Twitter](https://twitter.com/FormerLurker1).

**Comment by FormerLurker** [comment]
It looks like the links to gcode, the log file, and your settings.json failed.  Can you attach those somehow (gist.github.com, dropbox, etc)?  Thank you for the report!

**Comment by sr1329** [comment]
Sorry I just got around to it. Octoprint.log is too big for Pastebin. Thank you for looking over all of this.

**Comment by FormerLurker** [comment]
No problem, this is a busy time of the year for me anyway, so I've been pretty slow to respond myself (I am usually very prompt).

I will review these logs ASAP, thanks!

**Comment by GB560** [comment]
@sr1329 did you ever figure this out? I am having the same issue

**Comment by FormerLurker** [comment]
Sorry, no.  It has something to do with the Pi4.  I have one on order.

**Comment by sr1329** [comment]
Honestly I haven’t checked. I switched to a 4GB pi 4. It seems due to the 64 bit OS needed by the 8GB model.

On Nov 17, 2020, at 9:19 AM, GB560 <notifications@github.com> wrote:

﻿

@sr1329<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_sr1329&d=DwMCaQ&c=slrrB7dE8n7gBJbeO0g-IQ&r=i0iMjlNrlUgfsH63L7eELQ&m=Kmwm2XVts8YHKYem0i1_h9MI_hI7ZDzTzW0RU702JAI&s=2AsnB_SWjo3julxrfGyxm1LpijJcv61ubJ5GH5RgfEs&e=> did you ever figure this out? I am having the same issue

**Comment by FormerLurker** [comment]
@sr1329 , can you try installing from the plugin manager using this link in the From Url... box: https://github.com/FormerLurker/Octolapse/archive/88aa71f0fbac306b0d9acf19dff7388a30b29b64.zip

See if that fixes it.

**Comment by GB560** [comment]
@FormerLurker I tried it, worked like a charm! Thank you!

**Comment by FormerLurker** [comment]
Thank @tech2077, who figured out what was going on.  Turns out converting bool values to long ints doesn't work well with certain compiler optimizations.  Anyway, thanks for testing it out!  This will go live soon.

**Comment by FormerLurker** [comment]
This should be fixed in V0.4.1, which just dropped. Might take a while to show up in the plugin manager. Reopen a new issue if you continue to have problems. Thanks!
