### ISSUE TITLE
Focus not maintained during print

### ISSUE THREAD

**Issue by MoX46** [FormerLurker/Octolapse#649]
#### Version of Octolapse
 
Octolapse Version: 0.4.1

#### Version of OctoPrint

OctoPrint Version: 1.5.2

#### When you ran into the problem, did you have diagnostic logging enabled?

Diagnostic Logging was Enabled: Yes

#### What were you doing when the problem occurred

1. Set focus to manual in the custom camera settings
2. Set absolute focus to the desired value (37 in my case)
3. Start printing

#### What should have happened?
Focus should remain constant throughout print.

#### What happened instead?
Print starts fine with the focus maintained as set in the custom camera settings. At some point during the print the focus changes by itself causing the following snapshots to be out of focus. When this happened, I checked the focus setting under the custom camera settings and it was the same as I had set it, but it had clearly changed. I tried to change the setting slightly (from 37 to 36) and the image came back into focus right away. 

#### Operating System running OctoPrint and Octolapse

OS Name: Linux (Debian)
Os Version: 10

#### Link to the gcode file you were printing when the problem occurred

Link to Gcode File: https://gist.github.com/MoX46/fa536e158422c1218ea27dac77b9b5e3

#### Link to settings.json

Link to settings.json with all passwords removed: https://gist.github.com/MoX46/944ffb7822d042540b8675ddd551a15b

#### Link to plugin_octolapse.log

Link to plugin_octolapse.log: N/A
I have had this problem before and so I set the logging to "Log Everything" which cacused the file to be more than 700,000 lines long. Gist crashes when I try to paste the log file in there!. I will be printing something else soon with logging set to Debug and can provide that file if needed.

#### Link to octoprint.log

Link to octoprint.log: https://gist.github.com/MoX46/58baad41ea934576c45265e9ac283578

#### Screenshots and/or videos of the problem:

Screenshot/Video Links: https://photos.app.goo.gl/swKP8qiywaMdEBQ48
**Note**: You can see the focus is OK at the start, then it goes out of focus around 4 second. The focus changes again later on but that was me changing it manually when I realized it was out of focus.

## Please consider becoming a patron
If you like this project, [please support my work by becoming a patron,](https://www.patreon.com/bePatron?u=9588101) and consider adding a 'star' to the repository.  It takes a lot of time and effort to maintain the project and respond to issues.  The cost of test prints, software, cameras, printer parts, etc. can quickly add up, so every bit helps.

You can find various [videos and tutorials](https://www.youtube.com/channel/UCnnTLQetNw7FqfQOLJCMqoQ) by subscribing to my Youtube channel.  You can also [follow me on Twitter](https://twitter.com/FormerLurker1).

**Comment by FormerLurker** [comment]
Sorry it took me a while to respond.  It looks like either the mjpegstreamer stream or the camera reset.  Unfortunately there is no way for Octolapse to handle this.  I would check the camera cable and see if it is loose.
