### ISSUE TITLE
Error with one layer object print

### ISSUE THREAD

**Issue by pierremilcent** [FormerLurker/Octolapse#651]
Using latest version there is an error message when trying to print and have octolapse when the object is only 1 layer height.

[plugin_octolapse.log](https://github.com/FormerLurker/Octolapse/files/5690088/plugin_octolapse.log)

**Comment by FormerLurker** [comment]
@pierremilcent, yeah, this 'should' have been true for all versions of Octolapse (if it isn't, then it is a bug).  You can't render a video with a single frame.  If you want to do a timelapse of a single layer, use the 'timer' trigger.

Thanks!
