### ISSUE TITLE
[Request] How to run octolapse on the TV box

### ISSUE THREAD

**Issue by dgpower** [FormerLurker/Octolapse#652]
如何在电视盒子上运行octolapse?

我已经用电视盒子安装了Octoprint、MJPG-STREAMER和octolapse插件。已经确认mjpg-streamer可以正常工作（因为我在Octoprint页面上看到了图像）。但是octolapse报告说没有发现摄像头。

我看到Octopi系统，需要修改boot目录下的octopi.txt文件，但显然我的不是pi，所以就没有这个文件。不知道是不是这个原因导致octolapse不能正常访问摄像头？

请问，我该如何配置才能让octolapse正常工作？
-----------------------------------------
I have installed Octoprint, MJPG-STREAMER and octolapse plug-ins with the TV box. It has been confirmed that mjpg-streamer can work normally (because I saw the image on the Octoprint page). But octolapse reported that no cameras were found.

I saw that the Octopi system needs to modify the octopi.txt file in the boot directory, but obviously mine is not pi, so there is no such file. I don’t know if this is the reason why octolapse cannot access the camera normally?

Excuse me, how can I configure to make octolapse work normally?

**Comment by FormerLurker** [comment]
Please post any and all error messages you saw, as well as the plugin.octolapse.log file.  Thanks!

**Comment by dgpower** [comment]
当我升级到最新版本的octolapse，一切正常了。非常感谢！
--------------------------------------------------------------
When I upgraded to the latest version of octolapse, everything worked fine. thank you very much!
