### ISSUE TITLE
Error Starting Timelapse

### ISSUE THREAD

**Issue by Octoprintz** [FormerLurker/Octolapse#656]
When I start a print with Octolapse enabled it will respond with Octolapse Startup Failed.

![Screenshot 2020-12-31 191745](https://user-images.githubusercontent.com/76828148/103431878-e3936080-4b9c-11eb-9c0d-7666412d5fef.png)

Printer name Geeetech A10T, 3 in 1 out
Octolapse Version 0.4.1
Octoprint Version 0.18.0, running on Raspberry Pi 4 Model B Rev 1.4

**Comment by Octoprintz** [comment]
### Error Details

2020-12-31 22:16:31,827 - octolapse.__init__ - ERROR - Unable to start the timelapse.
Traceback (most recent call last):
  File "/home/pi/oprint/lib/python3.7/site-packages/octoprint_octolapse/__init__.py", line 2427, in on_print_start
    timelapse_settings = self.get_timelapse_settings()
  File "/home/pi/oprint/lib/python3.7/site-packages/octoprint_octolapse/__init__.py", line 2666, in get_timelapse_settings
    success, error_type, error_list = current_printer_clone.get_gcode_settings_from_file(gcode_file_path)
  File "/home/pi/oprint/lib/python3.7/site-packages/octoprint_octolapse/settings.py", line 682, in get_gcode_settings_from_file
    new_slicer_settings.update_settings_from_gcode(new_settings, self)
  File "/home/pi/oprint/lib/python3.7/site-packages/octoprint_octolapse/settings.py", line 2789, in update_settings_from_gcode
    num_extruders = int(settings_dict["machine_extruder_count"])
TypeError: int() argument must be a string, a bytes-like object or a number, not 'NoneType'

**Comment by FormerLurker** [comment]
Post the gcode please.  Looks like some unexpected text in the slicer settings output.

**Comment by Octoprintz** [comment]
Here is the gcode file I tried octolapse with,

[GA_10mmcube (1).zip](https://github.com/FormerLurker/Octolapse/files/5758575/GA_10mmcube.1.zip)

**Comment by Octoprintz** [comment]
What changes do I need to make to my gcode?

**Comment by FormerLurker** [comment]
Do you have 3 extruders?  If not, you added the wrong script to the start gcode.  Try the single extruder script.

**Comment by Octoprintz** [comment]
The automatic configuration gcode was interfering with my gcode coloring app so I have decided not to use it, and yes I do have three extruders.

**Comment by Octoprintz** [comment]
Now that I am not using the automatic configuration Octolapse is working.

**Comment by Octoprintz** [comment]
And another problem, after the print head moves to take a snapshot then moves back it pauses for about 20 seconds.

**Comment by Octoprintz** [comment]
Ok I have also fixed that  so I will close this issue
