### ISSUE TITLE
List in Octoprint Plugin Repo

### ISSUE THREAD

**Issue by stampede-arm** [FormerLurker/Octolapse#67]
It'd be nice (and more exposure) if this was listed in the Plugin Repo.

https://plugins.octoprint.org/help/registering/

**Comment by FormerLurker** [comment]
I'm glad you like it!  I'm working on getting it in the plugin repository,
but recent upgrades require Octoprint 1.3.7, which hasn't yet been
released.  I don't think it will be too long.

**Comment by FormerLurker** [comment]
We are on the repository!  

https://plugins.octoprint.org/plugins/octolapse/

Closed!
