### ISSUE TITLE
Unable to install Octolapse - MemoryError

### ISSUE THREAD

**Issue by grykom** [FormerLurker/Octolapse#703]
Hi guys, I have problem with install Octolapse on my Octoprint. 
I already tried:
'pip update' 
more voltage on rpi
searching google for solutions

#### Version of Octolapse
 
Octolapse Version: v0.4.1 (2020-12-05)

#### Version of OctoPrint

OctoPrint Version: 1.5.3

#### What were you doing when the problem occurred

1. search for Octolapse in plugins
2. click install button

#### What should have happened?
Octolapse should install

#### What happened instead?
An 'MemoryError' appears 

#### Operating System running OctoPrint and Octolapse

OS Name: OctoPi
Os Version: 0.16.0
OctoPrint 1.5.3
Python 2.7.13
Raspberry Pi 3B

#### Printer model & used firmware incl. version

Printer Model: ender 3
Printer Firmware Version: Klipper

#### Browser and version of browser, operating system running browser

Browser: Firefox / Chrome
Browser OS: Windows 10

#### Link to plugin_pluginmanager_console.log

Link to plugin_pluginmanager_console.log: https://pastebin.com/E2L1SFmr

#### Link to octoprint.log

Link to octoprint.log:  https://pastebin.com/4YS7jeUH

## Please consider becoming a patron
If you like this project, [please support my work by becoming a patron,](https://www.patreon.com/bePatron?u=9588101) and consider adding a 'star' to the repository.  It takes a lot of time and effort to maintain the project and respond to issues.  The cost of test prints, software, cameras, printer parts, etc. can quickly add up, so every bit helps.

You can find various [videos and tutorials](https://www.youtube.com/channel/UCnnTLQetNw7FqfQOLJCMqoQ) by subscribing to my Youtube channel.  You can also [follow me on Twitter](https://twitter.com/FormerLurker1).

**Comment by FormerLurker** [comment]
Hey, sorry I didn't see this earlier.  Been trying to get my printer working.  I hope you got your install issue solved!
