### ISSUE TITLE
Octolaps causing issues on surface of print

### ISSUE THREAD

**Issue by Greywolf98** [FormerLurker/Octolapse#733]
#### If this is a feature request describe it here

Octolaps causing remnants/surface artifacts

#### Version of Octolapse
 
Octolapse Version: v0.4.1

#### Version of OctoPrint

OctoPrint Version: v1.6.0

#### When you ran into the problem, did you have diagnostic logging enabled?

Diagnostic Logging was Enabled: NO

#### What were you doing when the problem occurred

1. when printing some models i noticed the remnants.
2. realized it was only occurring when i had octolaps enabled
3. attempted to alter settings to see if that was the issue

#### What should have happened?
 a semi clean or at least remnant free print

#### What happened instead?
any model that was printed with octolaps running generated ramnant or excess filiment on model during print

#### Operating System running OctoPrint and Octolapse

OS Name: octoPi
Os Version: v0.18.0

#### Printer model & used firmware incl. version

Printer Model: Ender 3 V2
Printer Firmware Version: development build: https://www.youtube.com/redirect?event=video_description&redir_token=QUFFLUhqa3JZOTJoUTZFZFhxXzNMZWRmWEo0dHJieFd3UXxBQ3Jtc0tsNHY1SjRaM3BHa2RoUzREWVc3ZTdrRmFDa1NKSTFDM0h6M3lfaEgtV0k4VjRCYS01NU9jcjRRRVR1Q0ZzWENSbTh0ZGNsYVUtcndfazhieHhsSkRDQzRlbldPQ0d6cDJNQ0ZDWlJyOF9sTkZVUGtTNA&q=https%3A%2F%2Fgithub.com%2Fcosmoderp%2FMarlin%2Ftree%2FEnder-3-v2-Advanced-Menu-9_18_20

#### Screenshots and/or videos of the problem:

Screenshot/Video Links:![20210506_192222](https://user-images.githubusercontent.com/83794395/117381439-b5eb5a80-aea1-11eb-9bdf-aa166c6ec1fe.jpg)
![20210506_192135](https://user-images.githubusercontent.com/83794395/117381458-bedc2c00-aea1-11eb-84bd-fe91453e2a39.jpg)
![20210506_192140](https://user-images.githubusercontent.com/83794395/117381461-c00d5900-aea1-11eb-83ef-0ac08e00aa70.jpg)
![20210506_192211](https://user-images.githubusercontent.com/83794395/117381462-c0a5ef80-aea1-11eb-9f0f-3ce056f2418b.jpg)
![20210506_192217](https://user-images.githubusercontent.com/83794395/117381464-c1d71c80-aea1-11eb-81f8-6a21909499b1.jpg)
![20210506_192220](https://user-images.githubusercontent.com/83794395/117381466-c26fb300-aea1-11eb-8066-adaaefd1b28a.jpg)

## Please consider becoming a patron
If you like this project, [please support my work by becoming a patron,](https://www.patreon.com/bePatron?u=9588101) and consider adding a 'star' to the repository.  It takes a lot of time and effort to maintain the project and respond to issues.  The cost of test prints, software, cameras, printer parts, etc. can quickly add up, so every bit helps.

You can find various [videos and tutorials](https://www.youtube.com/channel/UCnnTLQetNw7FqfQOLJCMqoQ) by subscribing to my Youtube channel.  You can also [follow me on Twitter](https://twitter.com/FormerLurker1).

**Comment by FormerLurker** [comment]
I hope you were able to solve your issue.  Sorry I didn't get back to you sooner.  If you are still having problems, feel free to open it back up, thanks!
