### ISSUE TITLE
[Request] Add option to flip webcam vertically AND horizontally

### ISSUE THREAD

**Issue by Joedmin** [FormerLurker/Octolapse#752]
### Description

I have the pi cam v2 mounted to my printer, but it is upside down (cause of the better cable management - it won't get stuck etc.) so I'd need to add option to flip webcam vertically AND horizontally

## My specs

Printer: Ender 3
Device: Raspberry Pi 3
Camera: Pi Cam V2
Octolapse Version: 0.4.1
OctoPrint Version: 1.6.1

Thank you in advance!

**Comment by FormerLurker** [comment]
Will the 'rotate 180 degrees' option not work:

![image](https://user-images.githubusercontent.com/33363128/124782122-973d2a80-df09-11eb-92ea-8198220cb8b7.png)

**Comment by Joedmin** [comment]
Oh, yeah, it works, thank you! 😅
