### ISSUE TITLE
Setup Problem

### ISSUE THREAD

**Issue by interceptor70** [FormerLurker/Octolapse#85]
Error message : Unable to restore the default settings.  Status: error.  Error: INTERNAL SERVER ERROR

**Comment by FormerLurker** [comment]
@interceptor70 , I think this was fixed just a few moments ago.  If you installed Octolapse more than about 2 hours ago, please re-install and try again.  Very sorry for the inconvenience :(

**Comment by interceptor70** [comment]
Ok Thanks :) now it works.... :-) and now i will add an Irapid Black

**Comment by FormerLurker** [comment]
Superb.  And another printer profile, you're the best!  That a sweet looking printer, btw...

**Comment by FormerLurker** [comment]
I'm marking this as closed, please create a new issue to create the irapid black profile, upload your settings, and I'll add it to the defaults with a 'beta' tag.
