### ISSUE TITLE
Issue with plugin_requires

### ISSUE THREAD

**Issue by jneilliii** [FormerLurker/Octolapse#905]
https://github.com/FormerLurker/Octolapse/blob/c6c86782cdbfc3590fa4b1bf2e63064eb459b16b/setup.py#L54

Not sure if this is the reason, but received [this](https://community.octoprint.org/t/cant-install-plugins-after-linux-kubuntu-distro-update/51730/6?u=jneilliii) post in the forum. I think it's because there is a space after pillow.

**Comment by FormerLurker** [comment]
I have master now updated with the latest from the devel branch.  I just verified that it installs now from the master branch using this URL:

https://github.com/FormerLurker/Octolapse/archive/refs/heads/master.zip

Working on the release after I verify things.  There is a new feature in this release too that is not tested as well as I would like, so hopefullly that doesn't break things, lol!  I think it will be OK.
