### ISSUE TITLE
Add mm/s in addition to mm/min in printer configuration.

### ISSUE THREAD

**Issue by systemik** [FormerLurker/Octolapse#91]
#### If this is a feature request describe it here

Many person use mm/s to configure their printer / slicer. Can you add a new setting in the printer configuration page to chose between mm/min and mm/s? This will ease the creation/modification of printer templates for those using mm/s.

#### Version of Octolapse
 
Octolapse Version: V0.2.2

#### Version of OctoPrint

OctoPrint Version: 1.3.7rc2

**Comment by FormerLurker** [comment]
I'll definitely consider this!  There are a lot of units on the various settings pages, so it's not a small task.  Maybe there's an easy way to accomplish this that I'm not thinking of at the moment.

I'll think about this for a bit and will mark this as an enhancement now.

**Comment by systemik** [comment]
Quick win for you, waiting for full implementation, is to add a mm/s calculation info. No need to have mm/s entry at first but at least when you input mm/min, you'll know immediately what is the mm/s equivalent. This would need to ba added to the printer config page only (e.g. automatic divide by 60 info).

**Comment by FormerLurker** [comment]
Good idea!  Will probably do this.

**Comment by FormerLurker** [comment]
Well, I ended up adding a unit selector on the printer profile page.  This will be available when v0.2.6-beta is released.  It should be pretty soon unless I run into snags testing.

**Comment by FormerLurker** [comment]
Hey, this is now in version 0.3.1.  Let me know if you like it, and thanks for pushing me to do it.  The axis feedrate section is much nicer now :)

Closing the issue.
