### ISSUE TITLE
Anycubic I3 Mega beta profile

### ISSUE THREAD

**Issue by systemik** [FormerLurker/Octolapse#98]
#### If this is a feature request describe it here

Anycubic I3 Mega Beta Profile attached (working well for me)

#### Version of Octolapse
 
Octolapse Version: v0.2.2

#### Version of OctoPrint

OctoPrint Version: 1.3.7rc2

[Settings.zip](https://github.com/FormerLurker/Octolapse/files/1845509/Settings.zip)

**Comment by FormerLurker** [comment]
You're the best, thanks!

**Comment by FormerLurker** [comment]
Added to v0.2.4

**Comment by DapperB** [comment]
where do I put this?
